//! TypeScript binding generator.
//!
//! Turns parsed Soroban contract metadata ([`ContractMetadata`]) into a typed
//! TypeScript client, either as a single self-contained module (stdout mode)
//! or as a publishable npm package with CommonJS, ESM, or dual layouts.
//!
//! Output is fully deterministic: no timestamps, spec declaration order is
//! preserved, and [`write_generated_files`] only touches files whose contents
//! actually changed, so regenerated clients produce small, reviewable diffs.
//!
//! The generated client is transport-agnostic. Each typed method builds an
//! `InvokeRequest` object and hands it to a user supplied `Transport`
//! (for example one backed by `@stellar/stellar-sdk`), then maps
//! Soroban failure strings such as `Error(Contract, #3)` onto typed errors.
//! This keeps the generated package dependency-free and lets it compile under
//! `tsc --strict` without `node_modules`.

use super::{pascal_case, ContractEnum, ContractMetadata};
use anyhow::{bail, Context, Result};
use std::collections::{BTreeMap, BTreeSet};
use std::path::{Component, Path};

/// Banner placed at the top of every generated TypeScript source file.
pub const GENERATED_HEADER: &str =
    "// Generated by StarForge (`starforge contract generate-bindings --lang ts`).\n\
// DO NOT EDIT: regenerate from the contract spec instead.\n";

/// Name of the manifest written next to a generated package. It records the
/// files StarForge owns so stale ones can be removed on regeneration.
pub const MANIFEST_FILE: &str = ".starforge-bindings.json";

/// JavaScript module layout of a generated package.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TsModuleFormat {
    /// ES modules only (`"type": "module"`, `dist/esm`).
    Esm,
    /// CommonJS only (`dist/cjs`).
    Cjs,
    /// Both, selected through conditional `exports` (`import` / `require`).
    Dual,
}

impl TsModuleFormat {
    pub fn as_str(self) -> &'static str {
        match self {
            TsModuleFormat::Esm => "esm",
            TsModuleFormat::Cjs => "cjs",
            TsModuleFormat::Dual => "dual",
        }
    }

    fn has_esm(self) -> bool {
        matches!(self, TsModuleFormat::Esm | TsModuleFormat::Dual)
    }

    fn has_cjs(self) -> bool {
        matches!(self, TsModuleFormat::Cjs | TsModuleFormat::Dual)
    }
}

/// Options for [`generate_typescript_package`].
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TsPackageOptions {
    /// npm package name (validated; may be scoped, e.g. `@acme/token-client`).
    pub package_name: String,
    /// Package version written to `package.json`.
    pub version: String,
    /// Module layout.
    pub module: TsModuleFormat,
}

impl TsPackageOptions {
    pub fn new(package_name: impl Into<String>, module: TsModuleFormat) -> Self {
        Self {
            package_name: package_name.into(),
            version: "0.1.0".to_string(),
            module,
        }
    }
}

/// One generated file, with a `/`-separated path relative to the output dir.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedFile {
    pub path: String,
    pub contents: String,
}

/// What [`write_generated_files`] did (or would do, in check mode).
#[derive(Debug, Default, Clone, PartialEq, Eq)]
pub struct WriteReport {
    pub created: Vec<String>,
    pub updated: Vec<String>,
    pub unchanged: Vec<String>,
    pub removed: Vec<String>,
}

impl WriteReport {
    /// `true` when the output directory already matched the generated files.
    pub fn is_clean(&self) -> bool {
        self.created.is_empty() && self.updated.is_empty() && self.removed.is_empty()
    }
}

/// Derive a valid npm package name from a contract file stem
/// (`my_token.wasm` becomes `my-token-client`).
pub fn default_package_name(stem: &str) -> String {
    let mut out = String::new();
    for ch in stem.chars() {
        let ch = ch.to_ascii_lowercase();
        if ch.is_ascii_lowercase() || ch.is_ascii_digit() {
            out.push(ch);
        } else if !out.ends_with('-') {
            out.push('-');
        }
    }
    let trimmed = out.trim_matches('-');
    if trimmed.is_empty() {
        "contract-client".to_string()
    } else {
        format!("{}-client", trimmed)
    }
}

/// Validate an npm package name (subset of the npm rules that matters here).
pub fn validate_package_name(name: &str) -> Result<()> {
    let valid_part = |part: &str| {
        !part.is_empty()
            && !part.starts_with('.')
            && !part.starts_with('_')
            && part.chars().all(|c| {
                c.is_ascii_lowercase() || c.is_ascii_digit() || matches!(c, '-' | '.' | '_' | '~')
            })
    };
    let ok = name.len() <= 214
        && match name.strip_prefix('@') {
            Some(scoped) => match scoped.split_once('/') {
                Some((scope, pkg)) => valid_part(scope) && valid_part(pkg),
                None => false,
            },
            None => valid_part(name),
        };
    if !ok {
        bail!(
            "Invalid npm package name '{}': use lowercase letters, digits, '-', '.', '_' or '~' (optionally scoped as @scope/name)",
            name
        );
    }
    Ok(())
}

/// Generate a single self-contained TypeScript module (types, error mapping,
/// and client) for `metadata`.
pub fn generate_single_file(metadata: &ContractMetadata) -> Result<String> {
    let model = Model::build(metadata)?;
    let mut out = String::from(GENERATED_HEADER);
    out.push('\n');
    out.push_str(&model.errors_body());
    out.push('\n');
    out.push_str(&model.types_body());
    out.push('\n');
    out.push_str(&model.client_body());
    Ok(out)
}

/// Generate a complete npm package for `metadata`.
///
/// Files are returned sorted by path so callers (and tests) get a stable
/// order. The list includes the [`MANIFEST_FILE`].
pub fn generate_typescript_package(
    metadata: &ContractMetadata,
    options: &TsPackageOptions,
) -> Result<Vec<GeneratedFile>> {
    validate_package_name(&options.package_name)?;
    let model = Model::build(metadata)?;
    let format = options.module;

    let mut files: BTreeMap<String, String> = BTreeMap::new();
    files.insert("src/errors.ts".into(), model.errors_module());
    files.insert("src/types.ts".into(), model.types_module());
    files.insert("src/client.ts".into(), model.client_module());
    files.insert("src/index.ts".into(), index_module());
    files.insert("package.json".into(), package_json(options));
    files.insert("tsconfig.json".into(), base_tsconfig());
    if format.has_esm() {
        files.insert("tsconfig.esm.json".into(), esm_tsconfig());
    }
    if format.has_cjs() {
        files.insert("tsconfig.cjs.json".into(), cjs_tsconfig());
    }
    if format == TsModuleFormat::Dual {
        files.insert("scripts/mark-cjs.cjs".into(), MARK_CJS_SCRIPT.to_string());
    }
    files.insert("README.md".into(), package_readme(&model, options));

    let manifest = manifest_json(format, files.keys());
    files.insert(MANIFEST_FILE.into(), manifest);

    Ok(files
        .into_iter()
        .map(|(path, contents)| GeneratedFile { path, contents })
        .collect())
}

/// Write `files` under `out_dir`, touching only files whose contents changed.
///
/// Files listed in a previous [`MANIFEST_FILE`] but no longer generated (for
/// example `tsconfig.esm.json` after switching from `dual` to `cjs`) are
/// removed. With `check_only`, nothing is written and the report describes
/// the changes that would be made.
pub fn write_generated_files(
    out_dir: &Path,
    files: &[GeneratedFile],
    check_only: bool,
) -> Result<WriteReport> {
    let mut report = WriteReport::default();
    let new_paths: BTreeSet<&str> = files.iter().map(|f| f.path.as_str()).collect();

    for path in previous_manifest_files(out_dir)? {
        if new_paths.contains(path.as_str()) {
            continue;
        }
        let target = out_dir.join(&path);
        if target.is_file() {
            if !check_only {
                std::fs::remove_file(&target)
                    .with_context(|| format!("Failed to remove stale {}", target.display()))?;
            }
            report.removed.push(path);
        }
    }

    for file in files {
        ensure_relative(&file.path)?;
        let target = out_dir.join(&file.path);
        let existing = std::fs::read(&target).ok();
        match existing {
            Some(bytes) if bytes == file.contents.as_bytes() => {
                report.unchanged.push(file.path.clone());
                continue;
            }
            Some(_) => report.updated.push(file.path.clone()),
            None => report.created.push(file.path.clone()),
        }
        if !check_only {
            if let Some(parent) = target.parent() {
                std::fs::create_dir_all(parent)
                    .with_context(|| format!("Failed to create {}", parent.display()))?;
            }
            std::fs::write(&target, &file.contents)
                .with_context(|| format!("Failed to write {}", target.display()))?;
        }
    }
    Ok(report)
}

fn previous_manifest_files(out_dir: &Path) -> Result<Vec<String>> {
    let path = out_dir.join(MANIFEST_FILE);
    let Ok(text) = std::fs::read_to_string(&path) else {
        return Ok(Vec::new());
    };
    let value: serde_json::Value = serde_json::from_str(&text)
        .with_context(|| format!("Failed to parse {}", path.display()))?;
    let mut files = Vec::new();
    if let Some(list) = value.get("files").and_then(|v| v.as_array()) {
        for entry in list {
            if let Some(rel) = entry.as_str() {
                // Never follow a manifest entry outside the output directory.
                if ensure_relative(rel).is_ok() {
                    files.push(rel.to_string());
                }
            }
        }
    }
    Ok(files)
}

fn ensure_relative(path: &str) -> Result<()> {
    let p = Path::new(path);
    if path.is_empty() || !p.components().all(|c| matches!(c, Component::Normal(_))) {
        bail!("Refusing to write generated file outside the output directory: {path}");
    }
    Ok(())
}

// ── Type expressions ─────────────────────────────────────────────────────────

/// Parsed form of the spec type strings stored in [`ContractMetadata`].
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) enum TypeExpr {
    Bool,
    U32,
    I32,
    U64,
    I64,
    U128,
    I128,
    U256,
    I256,
    String,
    Symbol,
    Address,
    Bytes,
    BytesN(u32),
    Void,
    Val,
    Error,
    Option(Box<TypeExpr>),
    Result(Box<TypeExpr>, Box<TypeExpr>),
    Vec(Box<TypeExpr>),
    Map(Box<TypeExpr>, Box<TypeExpr>),
    Tuple(Vec<TypeExpr>),
    Udt(String),
}

pub(crate) fn parse_type(src: &str) -> Result<TypeExpr> {
    let s = src.trim();
    if s.is_empty() {
        bail!("empty type");
    }
    if let Some(rest) = s.strip_prefix('(') {
        let inner = rest
            .strip_suffix(')')
            .ok_or_else(|| anyhow::anyhow!("unbalanced tuple type '{s}'"))?;
        if inner.trim().is_empty() {
            return Ok(TypeExpr::Void);
        }
        let parts = split_top_level(inner)?;
        return Ok(TypeExpr::Tuple(
            parts
                .into_iter()
                .map(parse_type)
                .collect::<Result<Vec<_>>>()?,
        ));
    }
    if let Some(lt) = s.find('<') {
        let inner = s[lt + 1..]
            .strip_suffix('>')
            .ok_or_else(|| anyhow::anyhow!("unbalanced generic type '{s}'"))?;
        let head = s[..lt].trim();
        let parts = split_top_level(inner)?;
        let arg = |i: usize| parse_type(parts[i]).map(Box::new);
        return match (head, parts.len()) {
            ("Option", 1) => Ok(TypeExpr::Option(arg(0)?)),
            ("Vec", 1) => Ok(TypeExpr::Vec(arg(0)?)),
            ("Result", 2) => Ok(TypeExpr::Result(arg(0)?, arg(1)?)),
            ("Map", 2) => Ok(TypeExpr::Map(arg(0)?, arg(1)?)),
            ("BytesN", 1) => {
                let n = parts[0]
                    .trim()
                    .parse::<u32>()
                    .map_err(|_| anyhow::anyhow!("BytesN length must be an integer in '{s}'"))?;
                Ok(TypeExpr::BytesN(n))
            }
            _ => bail!("unsupported generic type '{s}'"),
        };
    }
    Ok(match s {
        "bool" => TypeExpr::Bool,
        "u32" => TypeExpr::U32,
        "i32" => TypeExpr::I32,
        "u64" | "Timepoint" | "Duration" => TypeExpr::U64,
        "i64" => TypeExpr::I64,
        "u128" => TypeExpr::U128,
        "i128" => TypeExpr::I128,
        "U256" | "u256" => TypeExpr::U256,
        "I256" | "i256" => TypeExpr::I256,
        "String" => TypeExpr::String,
        "Symbol" => TypeExpr::Symbol,
        "Address" => TypeExpr::Address,
        "Bytes" => TypeExpr::Bytes,
        "Val" => TypeExpr::Val,
        "Error" => TypeExpr::Error,
        other if is_spec_ident(other) => TypeExpr::Udt(other.to_string()),
        other => bail!("invalid type name '{other}'"),
    })
}

fn split_top_level(s: &str) -> Result<Vec<&str>> {
    let mut parts = Vec::new();
    let mut depth = 0i32;
    let mut start = 0;
    for (i, ch) in s.char_indices() {
        match ch {
            '<' | '(' => depth += 1,
            '>' | ')' => {
                depth -= 1;
                if depth < 0 {
                    bail!("unbalanced brackets in '{s}'");
                }
            }
            ',' if depth == 0 => {
                parts.push(&s[start..i]);
                start = i + 1;
            }
            _ => {}
        }
    }
    if depth != 0 {
        bail!("unbalanced brackets in '{s}'");
    }
    parts.push(&s[start..]);
    if parts.iter().any(|p| p.trim().is_empty()) {
        bail!("empty type parameter in '{s}'");
    }
    Ok(parts)
}

fn is_spec_ident(s: &str) -> bool {
    !s.is_empty() && s.chars().all(|c| c == '_' || c.is_ascii_alphanumeric())
}

fn is_ts_ident(s: &str) -> bool {
    let mut chars = s.chars();
    match chars.next() {
        Some(c) if c == '_' || c == '$' || c.is_ascii_alphabetic() => {}
        _ => return false,
    }
    chars.all(|c| c == '_' || c == '$' || c.is_ascii_alphanumeric())
}

/// Object property key: bare identifier when valid, quoted otherwise.
fn prop_key(name: &str) -> String {
    if is_ts_ident(name) {
        name.to_string()
    } else {
        js_str(name)
    }
}

/// Property access expression on `base`.
fn prop_access(base: &str, name: &str) -> String {
    if is_ts_ident(name) {
        format!("{base}.{name}")
    } else {
        format!("{base}[{}]", js_str(name))
    }
}

fn js_str(s: &str) -> String {
    serde_json::to_string(s).unwrap_or_else(|_| "\"\"".to_string())
}

/// Names that generated UDT / helper types must not shadow.
const RESERVED_TYPE_NAMES: &[&str] = &[
    "Array",
    "BigInt",
    "Boolean",
    "CallOptions",
    "CliInvocationOptions",
    "ContractClient",
    "ContractClientError",
    "ContractClientErrorKind",
    "ContractClientOptions",
    "ContractErrorDescriptor",
    "ContractMethodName",
    "Error",
    "InvokeArg",
    "InvokeRequest",
    "Map",
    "Number",
    "Object",
    "Option",
    "Partial",
    "Promise",
    "Readonly",
    "ReadonlyArray",
    "Record",
    "Result",
    "SorobanErrorInfo",
    "SorobanErrorType",
    "SorobanHostErrorCode",
    "String",
    "Symbol",
    "Transport",
    "Uint8Array",
    "CONTRACT_ERRORS",
    "CONTRACT_METHODS",
];

const RESERVED_MEMBER_NAMES: &[&str] = &["constructor", "contractId", "__transport", "__invoke"];

// ── Model ────────────────────────────────────────────────────────────────────

struct MethodModel {
    spec_name: String,
    ts_name: String,
    args_type: Option<String>,
    inputs: Vec<(String, TypeExpr, String)>,
    output: TypeExpr,
    output_raw: String,
    doc: String,
}

struct Model<'a> {
    meta: &'a ContractMetadata,
    /// Spec UDT name -> TypeScript type name.
    udts: BTreeMap<String, String>,
    methods: Vec<MethodModel>,
}

fn malformed(msg: impl std::fmt::Display) -> anyhow::Error {
    anyhow::anyhow!("Malformed contract spec: {msg}")
}

fn check_unique<'n>(what: &str, names: impl IntoIterator<Item = &'n str>) -> Result<()> {
    let mut seen = BTreeSet::new();
    for name in names {
        if !is_spec_ident(name) {
            return Err(malformed(format!("{what} has invalid name '{name}'")));
        }
        if !seen.insert(name) {
            return Err(malformed(format!("duplicate {what} '{name}'")));
        }
    }
    Ok(())
}

impl<'a> Model<'a> {
    fn build(meta: &'a ContractMetadata) -> Result<Self> {
        if meta.functions.is_empty() {
            bail!("No contract functions found in WASM metadata");
        }

        // Register every user-defined type under a collision-free TS name.
        let mut udts = BTreeMap::new();
        let mut taken: BTreeSet<String> =
            RESERVED_TYPE_NAMES.iter().map(|s| s.to_string()).collect();
        let udt_names = meta
            .structs
            .iter()
            .map(|s| s.name.as_str())
            .chain(meta.enums.iter().map(|e| e.name.as_str()))
            .chain(meta.unions.iter().map(|u| u.name.as_str()))
            .chain(meta.errors.iter().map(|e| e.name.as_str()));
        let udt_names: Vec<&str> = udt_names.collect();
        check_unique("type", udt_names.iter().copied())?;
        for name in &udt_names {
            let ts = unique_name(pascal_case(name), &mut taken, "Type");
            udts.insert(name.to_string(), ts);
        }
        for name in udts.values() {
            taken.insert(format!("{name}Event"));
        }

        let model_check = |raw: &str, ctx: &str| -> Result<TypeExpr> {
            let expr = parse_type(raw).map_err(|e| malformed(format!("{ctx}: {e}")))?;
            check_refs(&expr, &udts).map_err(|e| malformed(format!("{ctx}: {e}")))?;
            Ok(expr)
        };

        for s in &meta.structs {
            check_unique(
                &format!("field of struct '{}'", s.name),
                s.fields.iter().map(|f| f.name.as_str()),
            )?;
            for f in &s.fields {
                model_check(&f.type_name, &format!("field '{}.{}'", s.name, f.name))?;
            }
        }
        for e in meta.enums.iter().chain(meta.unions.iter()) {
            check_unique(
                &format!("variant of '{}'", e.name),
                e.variants.iter().map(|v| v.name.as_str()),
            )?;
            for v in &e.variants {
                if let Some(ty) = &v.type_name {
                    model_check(ty, &format!("variant '{}::{}'", e.name, v.name))?;
                }
            }
        }
        for e in &meta.enums {
            if is_c_like(e) {
                let mut values = BTreeSet::new();
                for (i, v) in e.variants.iter().enumerate() {
                    if !values.insert(v.value.unwrap_or(i as u32)) {
                        return Err(malformed(format!(
                            "duplicate discriminant in enum '{}' at '{}'",
                            e.name, v.name
                        )));
                    }
                }
            }
        }
        for e in &meta.errors {
            check_unique(
                &format!("case of error enum '{}'", e.name),
                e.cases.iter().map(|c| c.name.as_str()),
            )?;
            let mut codes = BTreeSet::new();
            for c in &e.cases {
                if !codes.insert(c.value) {
                    return Err(malformed(format!(
                        "duplicate error code {} in '{}'",
                        c.value, e.name
                    )));
                }
            }
        }
        for ev in &meta.events {
            for f in &ev.fields {
                model_check(
                    &f.type_name,
                    &format!("event field '{}.{}'", ev.name, f.name),
                )?;
            }
        }

        check_unique("function", meta.functions.iter().map(|f| f.name.as_str()))?;
        let mut members: BTreeSet<String> = RESERVED_MEMBER_NAMES
            .iter()
            .map(|s| s.to_string())
            .collect();
        let mut methods = Vec::new();
        for f in &meta.functions {
            check_unique(
                &format!("parameter of '{}'", f.name),
                f.inputs.iter().map(|i| i.name.as_str()),
            )?;
            let mut inputs = Vec::new();
            for i in &f.inputs {
                let expr =
                    model_check(&i.type_name, &format!("parameter '{}.{}'", f.name, i.name))?;
                inputs.push((i.name.clone(), expr, i.type_name.clone()));
            }
            let output_raw = f.output.clone().unwrap_or_else(|| "()".to_string());
            let output = model_check(&output_raw, &format!("return type of '{}'", f.name))?;
            // The constructor runs once at deploy time and cannot be invoked.
            if f.name == "__constructor" {
                continue;
            }
            let base = if is_ts_ident(&f.name) {
                f.name.clone()
            } else {
                format!("_{}", f.name)
            };
            let ts_name = unique_name(base, &mut members, "_");
            let args_type = if inputs.is_empty() {
                None
            } else {
                Some(unique_name(
                    format!("{}Args", pascal_case(&f.name)),
                    &mut taken,
                    "_",
                ))
            };
            methods.push(MethodModel {
                spec_name: f.name.clone(),
                ts_name,
                args_type,
                inputs,
                output,
                output_raw,
                doc: f.doc.clone(),
            });
        }
        if methods.is_empty() {
            bail!("No invocable contract functions found in WASM metadata");
        }

        Ok(Model {
            meta,
            udts,
            methods,
        })
    }

    fn ts(&self, t: &TypeExpr, uses: &mut BTreeSet<String>) -> String {
        match t {
            TypeExpr::Bool => "boolean".into(),
            TypeExpr::U32 | TypeExpr::I32 => "number".into(),
            TypeExpr::U64
            | TypeExpr::I64
            | TypeExpr::U128
            | TypeExpr::I128
            | TypeExpr::U256
            | TypeExpr::I256 => "bigint".into(),
            TypeExpr::String | TypeExpr::Symbol | TypeExpr::Address => "string".into(),
            TypeExpr::Bytes | TypeExpr::BytesN(_) => "Uint8Array".into(),
            TypeExpr::Void => "void".into(),
            TypeExpr::Val => "unknown".into(),
            TypeExpr::Error => {
                uses.insert("SorobanErrorInfo".into());
                "SorobanErrorInfo".into()
            }
            TypeExpr::Option(inner) => {
                uses.insert("Option".into());
                format!("Option<{}>", self.ts(inner, uses))
            }
            TypeExpr::Result(ok, err) => {
                uses.insert("Result".into());
                format!("Result<{}, {}>", self.ts(ok, uses), self.ts(err, uses))
            }
            TypeExpr::Vec(inner) => format!("Array<{}>", self.ts(inner, uses)),
            TypeExpr::Map(k, v) => format!("Map<{}, {}>", self.ts(k, uses), self.ts(v, uses)),
            TypeExpr::Tuple(items) => format!(
                "readonly [{}]",
                items
                    .iter()
                    .map(|i| self.ts(i, uses))
                    .collect::<Vec<_>>()
                    .join(", ")
            ),
            TypeExpr::Udt(name) => {
                let ts = self.udts.get(name).cloned().unwrap_or_else(|| name.clone());
                uses.insert(ts.clone());
                ts
            }
        }
    }

    /// The resolved (awaited) return type of a method. `Result<T, E>` is
    /// unwrapped to `T` because failures surface as thrown errors.
    fn return_ts(&self, m: &MethodModel, uses: &mut BTreeSet<String>) -> String {
        match &m.output {
            TypeExpr::Result(ok, _) => self.ts(ok, uses),
            other => self.ts(other, uses),
        }
    }

    fn error_enum_names(&self) -> BTreeSet<&str> {
        self.meta.errors.iter().map(|e| e.name.as_str()).collect()
    }

    // ── errors ───────────────────────────────────────────────────────────

    fn errors_module(&self) -> String {
        format!("{GENERATED_HEADER}\n{}", self.errors_body())
    }

    fn errors_body(&self) -> String {
        let mut out = String::from(ERRORS_PRELUDE);
        out.push('\n');
        for e in &self.meta.errors {
            let ts = &self.udts[&e.name];
            out.push_str(&jsdoc(
                "",
                &[format!(
                    "Error codes of the contract error enum `{}`.",
                    e.name
                )],
            ));
            out.push_str(&format!("export const {ts} = {{\n"));
            for c in &e.cases {
                if !c.doc.trim().is_empty() {
                    out.push_str(&jsdoc("  ", &doc_lines(&c.doc)));
                }
                out.push_str(&format!("  {}: {},\n", prop_key(&c.name), c.value));
            }
            out.push_str("} as const;\n");
            out.push_str(&format!(
                "export type {ts} = (typeof {ts})[keyof typeof {ts}];\n\n"
            ));
        }

        out.push_str(&jsdoc(
            "",
            &[
                "Every contract error code declared in the spec, keyed by code.".into(),
                "If two error enums reuse a code, the first declaration wins.".into(),
            ],
        ));
        out.push_str(
            "export const CONTRACT_ERRORS: Readonly<Partial<Record<number, ContractErrorDescriptor>>> = {",
        );
        let mut seen = BTreeSet::new();
        let mut rows = Vec::new();
        for e in &self.meta.errors {
            for c in &e.cases {
                if !seen.insert(c.value) {
                    continue;
                }
                let message = if c.doc.trim().is_empty() {
                    c.name.clone()
                } else {
                    c.doc.trim().replace('\n', " ")
                };
                rows.push(format!(
                    "  {}: {{ enumName: {}, name: {}, code: {}, message: {} }},\n",
                    c.value,
                    js_str(&e.name),
                    js_str(&c.name),
                    c.value,
                    js_str(&message)
                ));
            }
        }
        if rows.is_empty() {
            out.push_str("};\n");
        } else {
            out.push('\n');
            for row in rows {
                out.push_str(&row);
            }
            out.push_str("};\n");
        }
        out.push('\n');
        out.push_str(ERRORS_RUNTIME);
        out
    }

    // ── types ────────────────────────────────────────────────────────────

    fn types_module(&self) -> String {
        let mut uses = BTreeSet::new();
        let body = self.types_body_with(&mut uses);
        let mut out = format!("{GENERATED_HEADER}\n");
        if uses.contains("SorobanErrorInfo") {
            out.push_str("import type { SorobanErrorInfo } from \"./errors.js\";\n\n");
        }
        out.push_str(&body);
        out
    }

    fn types_body(&self) -> String {
        self.types_body_with(&mut BTreeSet::new())
    }

    fn types_body_with(&self, uses: &mut BTreeSet<String>) -> String {
        let mut out = String::from(TYPES_PRELUDE);

        for s in &self.meta.structs {
            let ts = &self.udts[&s.name];
            out.push('\n');
            out.push_str(&jsdoc("", &[format!("Contract struct `{}`.", s.name)]));
            out.push_str(&format!("export interface {ts} {{\n"));
            for f in &s.fields {
                out.push_str(&self.field_line(&f.name, &f.type_name, uses));
            }
            out.push_str("}\n");
        }

        for e in &self.meta.enums {
            out.push('\n');
            if is_c_like(e) {
                let ts = &self.udts[&e.name];
                out.push_str(&jsdoc("", &[format!("Contract enum `{}`.", e.name)]));
                out.push_str(&format!("export const {ts} = {{\n"));
                for (i, v) in e.variants.iter().enumerate() {
                    out.push_str(&format!(
                        "  {}: {},\n",
                        prop_key(&v.name),
                        v.value.unwrap_or(i as u32)
                    ));
                }
                out.push_str("} as const;\n");
                out.push_str(&format!(
                    "export type {ts} = (typeof {ts})[keyof typeof {ts}];\n"
                ));
            } else {
                out.push_str(&self.union_decl(e, "enum", uses));
            }
        }

        for u in &self.meta.unions {
            out.push('\n');
            out.push_str(&self.union_decl(u, "union", uses));
        }

        let error_names = self.error_enum_names();
        for ev in &self.meta.events {
            if error_names.contains(ev.name.as_str()) {
                continue;
            }
            out.push('\n');
            out.push_str(&jsdoc(
                "",
                &[format!("Payload of the `{}` event.", ev.name)],
            ));
            out.push_str(&format!(
                "export interface {}Event {{\n",
                pascal_case(&ev.name)
            ));
            for f in &ev.fields {
                out.push_str(&self.field_line(&f.name, &f.type_name, uses));
            }
            out.push_str("}\n");
        }
        out
    }

    fn field_line(&self, name: &str, raw: &str, uses: &mut BTreeSet<String>) -> String {
        // Validated in `Model::build`, so parsing cannot fail here.
        let expr = parse_type(raw).unwrap_or(TypeExpr::Val);
        let optional = if matches!(expr, TypeExpr::Option(_)) {
            "?"
        } else {
            ""
        };
        format!(
            "  {}{}: {};\n",
            prop_key(name),
            optional,
            self.ts(&expr, uses)
        )
    }

    fn union_decl(&self, e: &ContractEnum, kind: &str, uses: &mut BTreeSet<String>) -> String {
        let ts = &self.udts[&e.name];
        let mut out = jsdoc(
            "",
            &[format!(
                "Contract {kind} `{}`, as a discriminated union on `tag`.",
                e.name
            )],
        );
        if e.variants.is_empty() {
            out.push_str(&format!("export type {ts} = never;\n"));
            return out;
        }
        out.push_str(&format!("export type {ts} =\n"));
        let last = e.variants.len() - 1;
        for (i, v) in e.variants.iter().enumerate() {
            let values = v
                .type_name
                .as_deref()
                .map(|raw| parse_type(raw).unwrap_or(TypeExpr::Val))
                .and_then(|expr| match expr {
                    TypeExpr::Void => None,
                    TypeExpr::Tuple(items) => Some(format!(
                        "readonly [{}]",
                        items
                            .iter()
                            .map(|t| self.ts(t, uses))
                            .collect::<Vec<_>>()
                            .join(", ")
                    )),
                    other => Some(format!("readonly [{}]", self.ts(&other, uses))),
                });
            let member = match values {
                Some(values) => format!(
                    "{{ readonly tag: {}; readonly values: {values} }}",
                    js_str(&v.name)
                ),
                None => format!("{{ readonly tag: {} }}", js_str(&v.name)),
            };
            let end = if i == last { ";" } else { "" };
            out.push_str(&format!("  | {member}{end}\n"));
        }
        out
    }

    // ── client ───────────────────────────────────────────────────────────

    fn client_module(&self) -> String {
        let mut uses = BTreeSet::new();
        let body = self.client_body_with(&mut uses);
        let mut out = format!("{GENERATED_HEADER}\n");
        out.push_str("import { mapSorobanError } from \"./errors.js\";\n");
        let from_errors: Vec<&str> = uses
            .iter()
            .map(|s| s.as_str())
            .filter(|s| *s == "SorobanErrorInfo")
            .collect();
        if !from_errors.is_empty() {
            out.push_str(&format!(
                "import type {{ {} }} from \"./errors.js\";\n",
                from_errors.join(", ")
            ));
        }
        let from_types: Vec<&str> = uses
            .iter()
            .map(|s| s.as_str())
            .filter(|s| *s != "SorobanErrorInfo")
            .collect();
        if !from_types.is_empty() {
            out.push_str(&format!(
                "import type {{ {} }} from \"./types.js\";\n",
                from_types.join(", ")
            ));
        }
        out.push('\n');
        out.push_str(&body);
        out
    }

    fn client_body(&self) -> String {
        self.client_body_with(&mut BTreeSet::new())
    }

    fn client_body_with(&self, uses: &mut BTreeSet<String>) -> String {
        let mut out = String::from(CLIENT_PRELUDE);

        out.push('\n');
        out.push_str(&jsdoc(
            "",
            &["Spec of every invocable contract function, in declaration order.".into()],
        ));
        out.push_str("export const CONTRACT_METHODS = {\n");
        for m in &self.methods {
            out.push_str(&format!("  {}: {{\n", prop_key(&m.spec_name)));
            if m.inputs.is_empty() {
                out.push_str("    args: [],\n");
            } else {
                out.push_str("    args: [\n");
                for (name, _, raw) in &m.inputs {
                    out.push_str(&format!(
                        "      {{ name: {}, type: {} }},\n",
                        js_str(name),
                        js_str(raw)
                    ));
                }
                out.push_str("    ],\n");
            }
            out.push_str(&format!("    returns: {},\n", js_str(&m.output_raw)));
            out.push_str("  },\n");
        }
        out.push_str("} as const;\n\n");
        out.push_str("/** Name of an invocable contract function. */\n");
        out.push_str("export type ContractMethodName = keyof typeof CONTRACT_METHODS;\n");

        for m in &self.methods {
            let Some(args_type) = &m.args_type else {
                continue;
            };
            out.push('\n');
            out.push_str(&jsdoc(
                "",
                &[format!(
                    "Arguments of the `{}` contract function.",
                    m.spec_name
                )],
            ));
            out.push_str(&format!("export interface {args_type} {{\n"));
            for (name, expr, _) in &m.inputs {
                let optional = if matches!(expr, TypeExpr::Option(_)) {
                    "?"
                } else {
                    ""
                };
                out.push_str(&format!(
                    "  {}{}: {};\n",
                    prop_key(name),
                    optional,
                    self.ts(expr, uses)
                ));
            }
            out.push_str("}\n");
        }

        out.push('\n');
        out.push_str(CLIENT_CLASS_HEAD);
        for m in &self.methods {
            out.push('\n');
            out.push_str(&self.method(m, uses));
        }
        out.push_str("}\n\n");
        out.push_str(CLIENT_CLI_HELPERS);
        out
    }

    fn method(&self, m: &MethodModel, uses: &mut BTreeSet<String>) -> String {
        let signature = format!(
            "`{}({}) -> {}`",
            m.spec_name,
            m.inputs
                .iter()
                .map(|(n, _, raw)| format!("{n}: {raw}"))
                .collect::<Vec<_>>()
                .join(", "),
            m.output_raw
        );
        let mut doc = doc_lines(&m.doc);
        if !doc.is_empty() {
            doc.push(String::new());
        }
        doc.push(format!("Contract signature: {signature}"));
        doc.push(
            "@throws {ContractClientError} when the call fails; contract error codes are decoded via `CONTRACT_ERRORS`."
                .into(),
        );
        let mut out = jsdoc("  ", &doc);

        let ret = self.return_ts(m, uses);
        let params = match &m.args_type {
            Some(args_type) => format!("args: {args_type}, options: CallOptions = {{}}"),
            None => "options: CallOptions = {}".to_string(),
        };
        out.push_str(&format!(
            "  async {}({params}): Promise<{ret}> {{\n",
            m.ts_name
        ));
        let call_args = if m.inputs.is_empty() {
            "[]".to_string()
        } else {
            let mut s = String::from("[\n");
            for (name, _, raw) in &m.inputs {
                s.push_str(&format!(
                    "        {{ name: {}, type: {}, value: {} }},\n",
                    js_str(name),
                    js_str(raw),
                    prop_access("args", name)
                ));
            }
            s.push_str("      ]");
            s
        };
        let invoke = format!(
            "this.__invoke(\n      {},\n      {call_args},\n      options,\n    )",
            js_str(&m.spec_name)
        );
        if ret == "void" {
            out.push_str(&format!("    await {invoke};\n"));
        } else {
            out.push_str(&format!("    const result = await {invoke};\n"));
            out.push_str(&format!("    return result as {ret};\n"));
        }
        out.push_str("  }\n");
        out
    }
}

fn check_refs(expr: &TypeExpr, udts: &BTreeMap<String, String>) -> Result<()> {
    match expr {
        TypeExpr::Udt(name) if !udts.contains_key(name) => {
            bail!("reference to undeclared type '{name}'")
        }
        TypeExpr::Option(i) | TypeExpr::Vec(i) => check_refs(i, udts),
        TypeExpr::Result(a, b) | TypeExpr::Map(a, b) => {
            check_refs(a, udts)?;
            check_refs(b, udts)
        }
        TypeExpr::Tuple(items) => items.iter().try_for_each(|i| check_refs(i, udts)),
        _ => Ok(()),
    }
}

fn is_c_like(e: &ContractEnum) -> bool {
    e.variants.iter().all(|v| v.type_name.is_none())
}

fn unique_name(base: String, taken: &mut BTreeSet<String>, suffix: &str) -> String {
    let mut name = base;
    while taken.contains(&name) {
        name.push_str(suffix);
    }
    taken.insert(name.clone());
    name
}

fn doc_lines(doc: &str) -> Vec<String> {
    doc.trim()
        .lines()
        .map(|l| l.trim_end().to_string())
        .collect()
}

fn jsdoc(indent: &str, lines: &[String]) -> String {
    let safe = |l: &str| l.replace("*/", "*\\/");
    if lines.len() == 1 {
        return format!("{indent}/** {} */\n", safe(&lines[0]));
    }
    let mut out = format!("{indent}/**\n");
    for l in lines {
        if l.is_empty() {
            out.push_str(&format!("{indent} *\n"));
        } else {
            out.push_str(&format!("{indent} * {}\n", safe(l)));
        }
    }
    out.push_str(&format!("{indent} */\n"));
    out
}

// ── Package scaffolding ──────────────────────────────────────────────────────

fn index_module() -> String {
    format!(
        "{GENERATED_HEADER}\nexport * from \"./errors.js\";\nexport * from \"./types.js\";\nexport * from \"./client.js\";\n"
    )
}

const MARK_CJS_SCRIPT: &str = "// Generated by StarForge. Marks dist/cjs as CommonJS inside a \"type\": \"module\" package.\n\
const fs = require(\"fs\");\n\
const path = require(\"path\");\n\
const target = path.join(__dirname, \"..\", \"dist\", \"cjs\", \"package.json\");\n\
fs.mkdirSync(path.dirname(target), { recursive: true });\n\
fs.writeFileSync(target, JSON.stringify({ type: \"commonjs\" }) + \"\\n\");\n";

fn package_json(options: &TsPackageOptions) -> String {
    let name = js_str(&options.package_name);
    let version = js_str(&options.version);
    let (type_line, main, types, exports, build) = match options.module {
        TsModuleFormat::Esm => (
            "  \"type\": \"module\",\n",
            "./dist/esm/index.js",
            "./dist/esm/index.d.ts",
            "    \".\": {\n      \"types\": \"./dist/esm/index.d.ts\",\n      \"import\": \"./dist/esm/index.js\",\n      \"default\": \"./dist/esm/index.js\"\n    },\n",
            "tsc -p tsconfig.esm.json",
        ),
        TsModuleFormat::Cjs => (
            "",
            "./dist/cjs/index.js",
            "./dist/cjs/index.d.ts",
            "    \".\": {\n      \"types\": \"./dist/cjs/index.d.ts\",\n      \"require\": \"./dist/cjs/index.js\",\n      \"default\": \"./dist/cjs/index.js\"\n    },\n",
            "tsc -p tsconfig.cjs.json",
        ),
        TsModuleFormat::Dual => (
            "  \"type\": \"module\",\n",
            "./dist/cjs/index.js",
            "./dist/cjs/index.d.ts",
            "    \".\": {\n      \"import\": {\n        \"types\": \"./dist/esm/index.d.ts\",\n        \"default\": \"./dist/esm/index.js\"\n      },\n      \"require\": {\n        \"types\": \"./dist/cjs/index.d.ts\",\n        \"default\": \"./dist/cjs/index.js\"\n      }\n    },\n",
            "tsc -p tsconfig.esm.json && tsc -p tsconfig.cjs.json && node scripts/mark-cjs.cjs",
        ),
    };
    let module_line = if options.module.has_esm() {
        "  \"module\": \"./dist/esm/index.js\",\n"
    } else {
        ""
    };
    format!(
        "{{\n  \"name\": {name},\n  \"version\": {version},\n  \"description\": \"Typed TypeScript client for a Soroban smart contract (generated by StarForge)\",\n  \"license\": \"MIT\",\n{type_line}  \"main\": \"{main}\",\n{module_line}  \"types\": \"{types}\",\n  \"exports\": {{\n{exports}    \"./package.json\": \"./package.json\"\n  }},\n  \"files\": [\n    \"dist\",\n    \"src\"\n  ],\n  \"sideEffects\": false,\n  \"scripts\": {{\n    \"build\": {},\n    \"typecheck\": \"tsc -p tsconfig.json\"\n  }},\n  \"devDependencies\": {{\n    \"typescript\": \">=5.0.0\"\n  }}\n}}\n",
        js_str(build)
    )
}

fn base_tsconfig() -> String {
    "{\n  \"compilerOptions\": {\n    \"target\": \"ES2020\",\n    \"lib\": [\"ES2020\"],\n    \"module\": \"ES2020\",\n    \"moduleResolution\": \"Bundler\",\n    \"strict\": true,\n    \"exactOptionalPropertyTypes\": true,\n    \"noUncheckedIndexedAccess\": true,\n    \"noImplicitOverride\": true,\n    \"noImplicitReturns\": true,\n    \"noFallthroughCasesInSwitch\": true,\n    \"noUnusedLocals\": true,\n    \"noUnusedParameters\": true,\n    \"forceConsistentCasingInFileNames\": true,\n    \"skipLibCheck\": true,\n    \"types\": [],\n    \"noEmit\": true\n  },\n  \"include\": [\"src\"]\n}\n"
        .to_string()
}

fn esm_tsconfig() -> String {
    "{\n  \"extends\": \"./tsconfig.json\",\n  \"compilerOptions\": {\n    \"noEmit\": false,\n    \"declaration\": true,\n    \"rootDir\": \"src\",\n    \"outDir\": \"dist/esm\"\n  }\n}\n"
        .to_string()
}

fn cjs_tsconfig() -> String {
    "{\n  \"extends\": \"./tsconfig.json\",\n  \"compilerOptions\": {\n    \"module\": \"CommonJS\",\n    \"moduleResolution\": \"Node10\",\n    \"noEmit\": false,\n    \"declaration\": true,\n    \"rootDir\": \"src\",\n    \"outDir\": \"dist/cjs\"\n  }\n}\n"
        .to_string()
}

fn manifest_json<'p>(format: TsModuleFormat, paths: impl Iterator<Item = &'p String>) -> String {
    let mut files: Vec<&str> = paths.map(|p| p.as_str()).collect();
    files.push(MANIFEST_FILE);
    files.sort_unstable();
    let list = files
        .iter()
        .map(|f| format!("    {}", js_str(f)))
        .collect::<Vec<_>>()
        .join(",\n");
    format!(
        "{{\n  \"generator\": \"starforge\",\n  \"language\": \"typescript\",\n  \"module\": \"{}\",\n  \"files\": [\n{list}\n  ]\n}}\n",
        format.as_str()
    )
}

fn package_readme(model: &Model<'_>, options: &TsPackageOptions) -> String {
    let mut methods = String::new();
    for m in &model.methods {
        methods.push_str(&format!("- `{}`\n", m.ts_name));
    }
    format!(
        "# {name}\n\n\
Typed TypeScript client for a Soroban smart contract, generated by\n\
[StarForge](https://github.com/Nanle-code/StarForge). Do not edit the\n\
files in `src/` by hand: regenerate them with\n\
`starforge contract generate-bindings <contract.wasm> --lang ts --out-dir <dir>`.\n\n\
Module layout: `{module}`.\n\n\
## Build\n\n\
```bash\nnpm install\nnpm run typecheck\nnpm run build\n```\n\n\
## Usage\n\n\
```ts\n\
import {{ ContractClient, isContractError, type Transport }} from \"{name}\";\n\n\
const transport: Transport = {{\n  async invoke(request, options) {{\n    // Simulate / sign / submit `request` with @stellar/stellar-sdk and return\n    // the native (scValToNative) result. See the StarForge TypeScript bindings guide.\n    throw new Error(`not implemented: ${{request.method}} ${{String(options.simulate)}}`);\n  }},\n}};\n\n\
const client = new ContractClient({{ contractId: \"C...\", transport }});\n\
```\n\n\
## Methods\n\n{methods}",
        name = options.package_name,
        module = options.module.as_str(),
    )
}

// ── Static TypeScript runtime pieces ─────────────────────────────────────────

const ERRORS_PRELUDE: &str = r#"/** Soroban host error categories (`ScErrorType`), indexed by XDR discriminant. */
export const SOROBAN_ERROR_TYPES = [
  "Contract",
  "WasmVm",
  "Context",
  "Storage",
  "Object",
  "Crypto",
  "Events",
  "Budget",
  "Value",
  "Auth",
] as const;
export type SorobanErrorType = (typeof SOROBAN_ERROR_TYPES)[number];

/** Soroban host error codes (`ScErrorCode`), indexed by XDR discriminant. */
export const SOROBAN_HOST_ERROR_CODES = [
  "ArithDomain",
  "IndexBounds",
  "InvalidInput",
  "MissingValue",
  "ExistingValue",
  "ExceededLimit",
  "InvalidAction",
  "InternalError",
  "UnexpectedType",
  "UnexpectedSize",
] as const;
export type SorobanHostErrorCode = (typeof SOROBAN_HOST_ERROR_CODES)[number];

/** Human readable descriptions of the host error codes. */
export const SOROBAN_HOST_ERROR_MESSAGES: Readonly<Record<SorobanHostErrorCode, string>> = {
  ArithDomain: "arithmetic overflow, underflow, or division by zero",
  IndexBounds: "index or key out of bounds",
  InvalidInput: "invalid input to a host function",
  MissingValue: "a required value (for example a ledger entry) is missing",
  ExistingValue: "a value that must not exist already exists",
  ExceededLimit: "a resource limit (CPU, memory, or size) was exceeded",
  InvalidAction: "the requested action is not permitted",
  InternalError: "internal host error",
  UnexpectedType: "a value had an unexpected type",
  UnexpectedSize: "a value had an unexpected size",
};

/** Transaction and InvokeHostFunction result codes reported by Stellar RPC / Horizon. */
export const TRANSACTION_RESULT_MESSAGES: Readonly<Partial<Record<string, string>>> = {
  txFAILED: "one or more operations failed",
  txTOO_EARLY: "the transaction time bounds start in the future",
  txTOO_LATE: "the transaction expired before it was included in a ledger",
  txMISSING_OPERATION: "the transaction has no operations",
  txBAD_SEQ: "the source account sequence number is wrong",
  txBAD_AUTH: "missing or invalid signatures",
  txINSUFFICIENT_BALANCE: "the source account cannot cover the fee and reserve",
  txNO_ACCOUNT: "the source account does not exist",
  txINSUFFICIENT_FEE: "the fee is below the network minimum",
  txBAD_AUTH_EXTRA: "unused signatures were attached",
  txINTERNAL_ERROR: "unknown stellar-core error",
  txSOROBAN_INVALID: "the Soroban transaction data is invalid",
  INVOKE_HOST_FUNCTION_MALFORMED: "the host function invocation is malformed",
  INVOKE_HOST_FUNCTION_TRAPPED: "the contract trapped (panicked or returned an error)",
  INVOKE_HOST_FUNCTION_RESOURCE_LIMIT_EXCEEDED: "declared Soroban resources were exceeded",
  INVOKE_HOST_FUNCTION_ENTRY_ARCHIVED: "a ledger entry used by the call is archived and must be restored",
  INVOKE_HOST_FUNCTION_INSUFFICIENT_REFUNDABLE_FEE: "the refundable fee is too low",
};

/** A decoded Soroban `Error(<type>, <code>)` value. */
export interface SorobanErrorInfo {
  readonly type: SorobanErrorType;
  /** Contract error code, or the host error code discriminant. */
  readonly code: number;
  /** Host error code name (absent for contract errors). */
  readonly codeName?: SorobanHostErrorCode;
}

/** Describes one contract-defined error code. */
export interface ContractErrorDescriptor {
  readonly enumName: string;
  readonly name: string;
  readonly code: number;
  readonly message: string;
}
"#;

const ERRORS_RUNTIME: &str = r#"/** Where a failure originated. */
export type ContractClientErrorKind = "contract" | "host" | "transaction" | "transport";

/** Error thrown by every generated client method. */
export class ContractClientError extends Error {
  readonly kind: ContractClientErrorKind;
  readonly soroban: SorobanErrorInfo | undefined;
  readonly contractError: ContractErrorDescriptor | undefined;
  readonly transactionCode: string | undefined;
  readonly original: unknown;

  constructor(
    message: string,
    details: {
      readonly kind: ContractClientErrorKind;
      readonly soroban?: SorobanErrorInfo | undefined;
      readonly contractError?: ContractErrorDescriptor | undefined;
      readonly transactionCode?: string | undefined;
      readonly original?: unknown;
    },
  ) {
    super(message);
    Object.setPrototypeOf(this, new.target.prototype);
    this.name = "ContractClientError";
    this.kind = details.kind;
    this.soroban = details.soroban;
    this.contractError = details.contractError;
    this.transactionCode = details.transactionCode;
    this.original = details.original;
  }
}

const SOROBAN_ERROR_PATTERN = /Error\(\s*([A-Za-z]+)\s*,\s*#?([A-Za-z0-9_]+)\s*\)/;
const TRANSACTION_CODE_PATTERN = /\b(tx[A-Z_]+|INVOKE_HOST_FUNCTION_[A-Z_]+)\b/;

function errorText(input: unknown): string {
  if (typeof input === "string") {
    return input;
  }
  if (input instanceof Error) {
    return input.message;
  }
  if (typeof input === "object" && input !== null) {
    const record = input as { readonly message?: unknown; readonly error?: unknown };
    if (typeof record.message === "string") {
      return record.message;
    }
    if (typeof record.error === "string") {
      return record.error;
    }
  }
  return String(input);
}

/**
 * Extract a Soroban `Error(<type>, <code>)` from an error, simulation
 * response, or diagnostic string, e.g. `Error(Contract, #3)` or
 * `Error(Storage, MissingValue)`.
 */
export function parseSorobanError(input: unknown): SorobanErrorInfo | undefined {
  const match = SOROBAN_ERROR_PATTERN.exec(errorText(input));
  if (match === null) {
    return undefined;
  }
  const typeText = match[1] ?? "";
  const codeText = match[2] ?? "";
  const type = SOROBAN_ERROR_TYPES.find((candidate) => candidate === typeText);
  if (type === undefined) {
    return undefined;
  }
  if (/^[0-9]+$/.test(codeText)) {
    const code = Number(codeText);
    const codeName =
      type === "Contract" ? undefined : SOROBAN_HOST_ERROR_CODES.find((_name, index) => index === code);
    return codeName === undefined ? { type, code } : { type, code, codeName };
  }
  const codeName = SOROBAN_HOST_ERROR_CODES.find((candidate) => candidate === codeText);
  if (codeName === undefined) {
    return undefined;
  }
  return { type, code: SOROBAN_HOST_ERROR_CODES.indexOf(codeName), codeName };
}

/** Convert any failure raised while invoking the contract into a `ContractClientError`. */
export function mapSorobanError(input: unknown): ContractClientError {
  if (input instanceof ContractClientError) {
    return input;
  }
  const text = errorText(input);
  const soroban = parseSorobanError(text);
  if (soroban !== undefined && soroban.type === "Contract") {
    const contractError = CONTRACT_ERRORS[soroban.code];
    const label =
      contractError === undefined
        ? `unknown contract error #${soroban.code}`
        : `${contractError.enumName}.${contractError.name} (#${soroban.code}): ${contractError.message}`;
    return new ContractClientError(`Contract call failed: ${label}`, {
      kind: "contract",
      soroban,
      contractError,
      original: input,
    });
  }
  if (soroban !== undefined) {
    const detail =
      soroban.codeName === undefined
        ? `code ${soroban.code}`
        : `${soroban.codeName}: ${SOROBAN_HOST_ERROR_MESSAGES[soroban.codeName]}`;
    return new ContractClientError(`Soroban host error (${soroban.type}, ${detail})`, {
      kind: "host",
      soroban,
      original: input,
    });
  }
  const transaction = TRANSACTION_CODE_PATTERN.exec(text);
  if (transaction !== null) {
    const code = transaction[1] ?? "";
    const description = TRANSACTION_RESULT_MESSAGES[code] ?? "transaction failed";
    return new ContractClientError(`Transaction failed (${code}): ${description}`, {
      kind: "transaction",
      transactionCode: code,
      original: input,
    });
  }
  return new ContractClientError(text, { kind: "transport", original: input });
}

/** Type guard for contract-defined failures, optionally matching a specific code. */
export function isContractError(error: unknown, code?: number): error is ContractClientError {
  return (
    error instanceof ContractClientError &&
    error.kind === "contract" &&
    (code === undefined || error.soroban?.code === code)
  );
}
"#;

const TYPES_PRELUDE: &str = r#"/** `Option<T>` in the contract spec; `undefined` encodes `None`. */
export type Option<T> = T | undefined;

/** `Result<T, E>` nested inside another type (top-level results are unwrapped). */
export type Result<T, E> =
  | { readonly ok: true; readonly value: T }
  | { readonly ok: false; readonly error: E };
"#;

const CLIENT_PRELUDE: &str = r#"/** One argument of an invocation, with its contract spec type (e.g. `u128`). */
export interface InvokeArg {
  readonly name: string;
  readonly type: string;
  readonly value: unknown;
}

/** Everything a transport needs to invoke a contract function. */
export interface InvokeRequest {
  readonly contractId: string;
  readonly method: string;
  readonly args: readonly InvokeArg[];
  /** Contract spec return type, e.g. `Result<u128, Error>`. */
  readonly returns: string;
}

/** Per-call options forwarded to the transport. */
export interface CallOptions {
  /** Only simulate the call (read-only); do not sign or submit. */
  readonly simulate?: boolean;
  /** Free-form data for custom transports (fees, signers, timeouts, ...). */
  readonly meta?: Readonly<Record<string, unknown>>;
}

/**
 * Executes invocations, typically with `@stellar/stellar-sdk`: encode the
 * arguments to ScVal, simulate, optionally sign and submit, and return the
 * native (`scValToNative`) result. Throwing is fine: errors are mapped to
 * `ContractClientError`.
 */
export interface Transport {
  invoke(request: InvokeRequest, options: CallOptions): Promise<unknown>;
}

export interface ContractClientOptions {
  readonly contractId: string;
  readonly transport: Transport;
}
"#;

const CLIENT_CLASS_HEAD: &str = r#"/** Typed client for the contract. */
export class ContractClient {
  readonly contractId: string;
  private readonly __transport: Transport;

  constructor(options: ContractClientOptions) {
    this.contractId = options.contractId;
    this.__transport = options.transport;
  }

  private async __invoke(
    method: ContractMethodName,
    args: readonly InvokeArg[],
    options: CallOptions,
  ): Promise<unknown> {
    const request: InvokeRequest = {
      contractId: this.contractId,
      method,
      args,
      returns: CONTRACT_METHODS[method].returns,
    };
    try {
      return await this.__transport.invoke(request, options);
    } catch (error) {
      throw mapSorobanError(error);
    }
  }
"#;

const CLIENT_CLI_HELPERS: &str = r#"/** Options for `toStarforgeCliArgs`. */
export interface CliInvocationOptions {
  readonly network?: string;
  readonly wallet?: string;
  /** Submit the transaction when a wallet is set (default `true`). */
  readonly submit?: boolean;
}

function toHex(bytes: Uint8Array): string {
  return Array.from(bytes, (byte) => byte.toString(16).padStart(2, "0")).join("");
}

/** Serialize an argument value the way `starforge contract invoke --arg` expects. */
export function serializeArg(value: unknown): string {
  if (typeof value === "string") {
    return value;
  }
  if (typeof value === "bigint" || typeof value === "number" || typeof value === "boolean") {
    return String(value);
  }
  if (value instanceof Uint8Array) {
    return toHex(value);
  }
  return JSON.stringify(value, (_key: string, inner: unknown) => {
    if (typeof inner === "bigint") {
      return inner.toString();
    }
    if (inner instanceof Uint8Array) {
      return toHex(inner);
    }
    if (inner instanceof Map) {
      return Object.fromEntries(inner);
    }
    return inner;
  }) ?? "null";
}

/** Build `starforge contract invoke ...` arguments for an invocation (useful in scripts and tests). */
export function toStarforgeCliArgs(request: InvokeRequest, options: CliInvocationOptions = {}): string[] {
  const cli = ["contract", "invoke", request.contractId, request.method, "--network", options.network ?? "testnet"];
  for (const arg of request.args) {
    cli.push("--arg", serializeArg(arg.value), "--type", arg.type);
  }
  if (options.wallet !== undefined) {
    cli.push("--wallet", options.wallet);
    if (options.submit !== false) {
      cli.push("--submit");
    }
  }
  return cli;
}
"#;

#[cfg(test)]
mod tests {
    use super::super::{
        complex_metadata, ContractField, ContractFunction, ContractInput, ContractStruct,
    };
    use super::*;

    fn minimal() -> ContractMetadata {
        ContractMetadata {
            functions: vec![ContractFunction {
                name: "hello".into(),
                inputs: vec![ContractInput {
                    name: "to".into(),
                    type_name: "Symbol".into(),
                }],
                output: Some("Vec<Symbol>".into()),
                doc: String::new(),
            }],
            structs: vec![],
            enums: vec![],
            events: vec![],
            unions: vec![],
            errors: vec![],
        }
    }

    #[test]
    fn parses_nested_types() {
        assert_eq!(
            parse_type("Map<Vec<u32>, (Address, Option<i128>)>").unwrap(),
            TypeExpr::Map(
                Box::new(TypeExpr::Vec(Box::new(TypeExpr::U32))),
                Box::new(TypeExpr::Tuple(vec![
                    TypeExpr::Address,
                    TypeExpr::Option(Box::new(TypeExpr::I128)),
                ])),
            )
        );
        assert_eq!(parse_type("()").unwrap(), TypeExpr::Void);
        assert_eq!(parse_type("BytesN<32>").unwrap(), TypeExpr::BytesN(32));
    }

    #[test]
    fn rejects_malformed_types() {
        for bad in [
            "",
            "Vec<u32",
            "Map<u32>",
            "Option<>",
            "(u32,,u32)",
            "Foo<u32>",
            "BytesN<x>",
            "a-b",
        ] {
            assert!(parse_type(bad).is_err(), "expected error for {bad:?}");
        }
    }

    #[test]
    fn single_file_is_deterministic_and_typed() {
        let meta = complex_metadata();
        let a = generate_single_file(&meta).unwrap();
        let b = generate_single_file(&meta).unwrap();
        assert_eq!(a, b);
        assert!(a.contains(
            "async balance_of(args: BalanceOfArgs, options: CallOptions = {}): Promise<bigint>"
        ));
        assert!(a.contains(
            "async transfer(args: TransferArgs, options: CallOptions = {}): Promise<void>"
        ));
        assert!(a.contains("memo?: Option<string>;"));
        assert!(a.contains("export const TransferError = {"));
        assert!(a.contains("10: { enumName: \"TransferError\", name: \"LimitExceeded\""));
        assert!(a.contains(
            "| { readonly tag: \"Allowance\"; readonly values: readonly [string, string] };"
        ));
        assert!(!a.contains("any"), "generated client must not use `any`");
    }

    #[test]
    fn rejects_undeclared_udt() {
        let mut meta = minimal();
        meta.functions[0].output = Some("Missing".into());
        let err = generate_single_file(&meta).unwrap_err().to_string();
        assert!(err.contains("Malformed contract spec"), "{err}");
        assert!(err.contains("undeclared type 'Missing'"), "{err}");
    }

    #[test]
    fn rejects_duplicates() {
        let mut meta = minimal();
        meta.functions.push(meta.functions[0].clone());
        assert!(generate_single_file(&meta)
            .unwrap_err()
            .to_string()
            .contains("duplicate function 'hello'"));

        let mut meta = minimal();
        meta.structs.push(ContractStruct {
            name: "Pair".into(),
            fields: vec![
                ContractField {
                    name: "a".into(),
                    type_name: "u32".into(),
                },
                ContractField {
                    name: "a".into(),
                    type_name: "u32".into(),
                },
            ],
        });
        assert!(generate_single_file(&meta)
            .unwrap_err()
            .to_string()
            .contains("duplicate field"));
    }

    #[test]
    fn rejects_empty_spec() {
        let mut meta = minimal();
        meta.functions.clear();
        assert!(generate_single_file(&meta).is_err());
    }

    #[test]
    fn renames_reserved_names() {
        let mut meta = minimal();
        meta.structs.push(ContractStruct {
            name: "Map".into(),
            fields: vec![],
        });
        meta.functions[0].name = "contractId".into();
        meta.functions[0].output = Some("Map".into());
        let out = generate_single_file(&meta).unwrap();
        assert!(out.contains("export interface MapType {"));
        assert!(out.contains("async contractId_(args: ContractIdArgs"));
        assert!(out.contains("Promise<MapType>"));
    }

    #[test]
    fn package_layouts() {
        let meta = complex_metadata();
        for (format, has_esm, has_cjs) in [
            (TsModuleFormat::Esm, true, false),
            (TsModuleFormat::Cjs, false, true),
            (TsModuleFormat::Dual, true, true),
        ] {
            let files =
                generate_typescript_package(&meta, &TsPackageOptions::new("token-client", format))
                    .unwrap();
            let paths: Vec<&str> = files.iter().map(|f| f.path.as_str()).collect();
            assert_eq!(paths.contains(&"tsconfig.esm.json"), has_esm);
            assert_eq!(paths.contains(&"tsconfig.cjs.json"), has_cjs);
            assert!(paths.contains(&"src/client.ts"));
            assert!(paths.contains(&MANIFEST_FILE));
            let mut sorted = paths.clone();
            sorted.sort_unstable();
            assert_eq!(paths, sorted, "files must be sorted for stable output");
            let pkg = &files
                .iter()
                .find(|f| f.path == "package.json")
                .unwrap()
                .contents;
            serde_json::from_str::<serde_json::Value>(pkg).expect("package.json is valid JSON");
            assert_eq!(pkg.contains("\"type\": \"module\""), has_esm);
        }
    }

    #[test]
    fn package_name_validation() {
        assert!(validate_package_name("token-client").is_ok());
        assert!(validate_package_name("@acme/token").is_ok());
        assert!(validate_package_name("Token").is_err());
        assert!(validate_package_name("@acme").is_err());
        assert!(validate_package_name("").is_err());
        assert_eq!(default_package_name("My_Token"), "my-token-client");
        assert_eq!(default_package_name("__"), "contract-client");
    }

    #[test]
    fn incremental_writes() {
        let dir = tempfile::tempdir().unwrap();
        let meta = complex_metadata();
        let dual = generate_typescript_package(
            &meta,
            &TsPackageOptions::new("token-client", TsModuleFormat::Dual),
        )
        .unwrap();
        let first = write_generated_files(dir.path(), &dual, false).unwrap();
        assert_eq!(first.created.len(), dual.len());

        let second = write_generated_files(dir.path(), &dual, false).unwrap();
        assert!(second.is_clean());
        assert_eq!(second.unchanged.len(), dual.len());

        let cjs = generate_typescript_package(
            &meta,
            &TsPackageOptions::new("token-client", TsModuleFormat::Cjs),
        )
        .unwrap();
        let check = write_generated_files(dir.path(), &cjs, true).unwrap();
        assert!(!check.is_clean());
        assert!(
            dir.path().join("tsconfig.esm.json").exists(),
            "check mode must not write"
        );

        let third = write_generated_files(dir.path(), &cjs, false).unwrap();
        assert!(third.removed.contains(&"tsconfig.esm.json".to_string()));
        assert!(third.removed.contains(&"scripts/mark-cjs.cjs".to_string()));
        assert!(third.updated.contains(&"package.json".to_string()));
        assert!(!dir.path().join("tsconfig.esm.json").exists());
    }

    #[test]
    fn rejects_escaping_paths() {
        assert!(ensure_relative("../x").is_err());
        assert!(ensure_relative("/etc/passwd").is_err());
        assert!(ensure_relative("src/index.ts").is_ok());
    }
}
