//! AI-assisted community analytics for the template marketplace.
//!
//! Resolves issue #532 ("AI Template Community Analysis") by aggregating
//! signals about how marketplace templates are actually used and received:
//!
//! - **Usage analytics** — locally logged scaffold/install/update events,
//!   combined with lifetime download counts from the registry.
//! - **Feedback analysis** — locally submitted ratings/comments
//!   (`starforge template feedback`), summarised into sentiment and common
//!   issue keywords.
//! - **Trend identification** — rising vs. declining templates, computed by
//!   comparing usage activity across two adjacent time windows.
//! - **Issue detection** — templates flagged for missing docs, deprecated
//!   maintenance status, unresolved security findings, malformed
//!   compatibility metadata, or a cluster of bug reports.
//! - **Improvement suggestions** — a rule-based engine that turns the above
//!   signals into concrete, actionable next steps.
//! - **Community insights** — cross-template rollups such as tag popularity
//!   and top contributing authors.
//!
//! An optional narrative summary can be generated by a locally running
//! Ollama model (see [`ai_narrative_summary`]); this is best-effort and the
//! deterministic report is always available even when Ollama is not
//! installed or not running.

use crate::utils::templates::{self, CompatibilityStatus, MaintenanceStatus, TemplateEntry};
use anyhow::{Context, Result};
use chrono::{DateTime, Duration, Utc};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::fs;
use std::io::{BufRead, BufReader, Write};
use std::path::{Path, PathBuf};
use std::str::FromStr;

// ─── Storage paths ──────────────────────────────────────────────────────────

fn analytics_dir() -> Result<PathBuf> {
    let dir = crate::utils::config::config_dir().join("analytics");
    if !dir.exists() {
        fs::create_dir_all(&dir).with_context(|| format!("Failed to create {}", dir.display()))?;
    }
    Ok(dir)
}

fn usage_log_path() -> Result<PathBuf> {
    Ok(analytics_dir()?.join("template_usage.jsonl"))
}

fn feedback_log_path() -> Result<PathBuf> {
    Ok(analytics_dir()?.join("template_feedback.jsonl"))
}

/// Append a JSON-serialisable value as a single line to `path` (JSON Lines format).
fn append_jsonl<T: Serialize>(path: &Path, value: &T) -> Result<()> {
    if let Some(parent) = path.parent() {
        if !parent.exists() {
            fs::create_dir_all(parent)?;
        }
    }
    let line = serde_json::to_string(value).context("Failed to serialize analytics event")?;
    let mut file = fs::OpenOptions::new()
        .create(true)
        .append(true)
        .open(path)
        .with_context(|| format!("Failed to open {}", path.display()))?;
    writeln!(file, "{}", line).with_context(|| format!("Failed to write to {}", path.display()))?;
    Ok(())
}

/// Load every well-formed JSON line from `path`. Missing files yield an empty
/// vector; malformed individual lines are skipped rather than failing the
/// whole load, so one corrupted entry can't hide the rest of the history.
fn load_jsonl<T: for<'de> Deserialize<'de>>(path: &Path) -> Result<Vec<T>> {
    if !path.exists() {
        return Ok(Vec::new());
    }
    let file =
        fs::File::open(path).with_context(|| format!("Failed to open {}", path.display()))?;
    let reader = BufReader::new(file);
    let mut out = Vec::new();
    for line in reader.lines() {
        let line = line?;
        if line.trim().is_empty() {
            continue;
        }
        if let Ok(value) = serde_json::from_str::<T>(&line) {
            out.push(value);
        }
    }
    Ok(out)
}

// ─── Usage tracking ─────────────────────────────────────────────────────────

/// The action a user took with respect to a template, recorded for usage analytics.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum UsageAction {
    /// Template used to scaffold a new contract via `starforge new contract`.
    Scaffold,
    /// Template installed via `starforge template install`.
    Install,
    /// An installed template was refreshed via `starforge template update`.
    Update,
}

impl UsageAction {
    pub fn label(&self) -> &'static str {
        match self {
            UsageAction::Scaffold => "scaffold",
            UsageAction::Install => "install",
            UsageAction::Update => "update",
        }
    }
}

/// A single locally logged usage event for a template.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UsageEvent {
    pub template: String,
    pub action: UsageAction,
    pub timestamp: DateTime<Utc>,
}

/// Record that `template` was used via `action`. Best-effort: callers should
/// treat failures as non-fatal (analytics must never break a working command).
pub fn record_usage(template: &str, action: UsageAction) -> Result<()> {
    record_usage_at(&usage_log_path()?, template, action)
}

fn record_usage_at(path: &Path, template: &str, action: UsageAction) -> Result<()> {
    let event = UsageEvent {
        template: template.to_string(),
        action,
        timestamp: Utc::now(),
    };
    append_jsonl(path, &event)
}

/// Load every locally logged usage event.
pub fn load_usage_events() -> Result<Vec<UsageEvent>> {
    load_jsonl(&usage_log_path()?)
}

// ─── Community feedback ─────────────────────────────────────────────────────

/// How a piece of free-text feedback was classified.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum FeedbackCategory {
    Bug,
    FeatureRequest,
    Praise,
    Question,
    Other,
}

impl FeedbackCategory {
    pub fn label(&self) -> &'static str {
        match self {
            FeedbackCategory::Bug => "bug",
            FeedbackCategory::FeatureRequest => "feature-request",
            FeedbackCategory::Praise => "praise",
            FeedbackCategory::Question => "question",
            FeedbackCategory::Other => "other",
        }
    }
}

impl FromStr for FeedbackCategory {
    type Err = anyhow::Error;

    fn from_str(s: &str) -> Result<Self> {
        match s.to_lowercase().replace(['_', ' '], "-").as_str() {
            "bug" | "issue" => Ok(FeedbackCategory::Bug),
            "feature-request" | "feature" | "request" => Ok(FeedbackCategory::FeatureRequest),
            "praise" | "positive" => Ok(FeedbackCategory::Praise),
            "question" => Ok(FeedbackCategory::Question),
            "other" => Ok(FeedbackCategory::Other),
            other => anyhow::bail!(
                "Unknown feedback category '{}': expected bug, feature-request, praise, question, or other",
                other
            ),
        }
    }
}

/// A single piece of community feedback submitted for a template.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FeedbackEntry {
    pub template: String,
    pub rating: Option<u8>,
    pub comment: String,
    pub category: FeedbackCategory,
    pub submitted_at: DateTime<Utc>,
}

const BUG_KEYWORDS: &[&str] = &[
    "bug",
    "crash",
    "error",
    "broken",
    "fails",
    "failing",
    "panic",
    "doesn't work",
    "does not work",
    "not working",
    "vulnerability",
    "exploit",
    "regression",
];
const FEATURE_KEYWORDS: &[&str] = &[
    "please add",
    "would be nice",
    "wish",
    "feature request",
    "support for",
    "it would be great",
    "can you add",
    "missing",
    "could you add",
    "feature:",
];
const PRAISE_KEYWORDS: &[&str] = &[
    "love",
    "great",
    "awesome",
    "excellent",
    "perfect",
    "thanks",
    "thank you",
    "amazing",
    "fantastic",
    "well done",
];

/// Heuristically classify free-text feedback when the caller doesn't supply
/// an explicit category. Keyword matching is intentionally simple and
/// transparent rather than a black box, so maintainers can trust the result.
pub fn classify_feedback(comment: &str, rating: Option<u8>) -> FeedbackCategory {
    let lower = comment.to_lowercase();

    if BUG_KEYWORDS.iter().any(|kw| lower.contains(kw)) {
        return FeedbackCategory::Bug;
    }
    if FEATURE_KEYWORDS.iter().any(|kw| lower.contains(kw)) {
        return FeedbackCategory::FeatureRequest;
    }
    if PRAISE_KEYWORDS.iter().any(|kw| lower.contains(kw)) {
        return FeedbackCategory::Praise;
    }
    if lower.trim_end().ends_with('?') {
        return FeedbackCategory::Question;
    }
    match rating {
        // A low rating with no other signal still points at a problem.
        Some(r) if r <= 2 => FeedbackCategory::Bug,
        Some(r) if r >= 5 => FeedbackCategory::Praise,
        _ => FeedbackCategory::Other,
    }
}

fn validate_feedback_input(comment: &str, rating: Option<u8>) -> Result<()> {
    if comment.trim().is_empty() {
        anyhow::bail!("Feedback comment cannot be empty");
    }
    if let Some(r) = rating {
        if !(1..=5).contains(&r) {
            anyhow::bail!("Rating must be between 1 and 5 (got {})", r);
        }
    }
    Ok(())
}

/// Submit a piece of community feedback for `template`, persisting it locally
/// so it can feed into future community analysis reports.
pub fn submit_feedback(
    template: &str,
    comment: &str,
    rating: Option<u8>,
    category: Option<FeedbackCategory>,
) -> Result<FeedbackEntry> {
    submit_feedback_at(&feedback_log_path()?, template, comment, rating, category)
}

fn submit_feedback_at(
    path: &Path,
    template: &str,
    comment: &str,
    rating: Option<u8>,
    category: Option<FeedbackCategory>,
) -> Result<FeedbackEntry> {
    validate_feedback_input(comment, rating)?;
    let category = category.unwrap_or_else(|| classify_feedback(comment, rating));
    let entry = FeedbackEntry {
        template: template.to_string(),
        rating,
        comment: comment.to_string(),
        category,
        submitted_at: Utc::now(),
    };
    append_jsonl(path, &entry)?;
    Ok(entry)
}

/// Load community feedback, optionally scoped to a single template.
pub fn load_feedback(template: Option<&str>) -> Result<Vec<FeedbackEntry>> {
    let all: Vec<FeedbackEntry> = load_jsonl(&feedback_log_path()?)?;
    Ok(match template {
        Some(name) => all.into_iter().filter(|f| f.template == name).collect(),
        None => all,
    })
}

// ─── Report data model ──────────────────────────────────────────────────────

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UsageAnalytics {
    /// Locally logged scaffold/install/update events in scope.
    pub total_logged_events: usize,
    /// Sum of `downloads` across templates in scope, from the registry.
    pub lifetime_downloads: u32,
    /// Templates ranked by locally logged activity, most active first.
    pub top_templates: Vec<(String, usize)>,
    /// Event counts grouped by action (scaffold/install/update).
    pub events_by_action: HashMap<String, usize>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct SentimentBreakdown {
    pub positive: usize,
    pub neutral: usize,
    pub negative: usize,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FeedbackAnalysis {
    pub total_feedback: usize,
    pub average_rating: Option<f32>,
    pub sentiment: SentimentBreakdown,
    /// Issue keywords found in bug-category comments, most frequent first.
    pub common_issues: Vec<(String, usize)>,
    /// Raw feature-request comments (capped), for maintainers to triage.
    pub feature_requests: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct TrendReport {
    pub rising: Vec<String>,
    pub declining: Vec<String>,
    pub steady: Vec<String>,
    pub window_days: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IssueFlag {
    pub template: String,
    pub reasons: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct IssueDetection {
    pub flagged: Vec<IssueFlag>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CommunityInsights {
    pub total_templates: usize,
    pub verified_pct: f32,
    pub documented_pct: f32,
    pub top_tags: Vec<(String, usize)>,
    pub top_authors: Vec<(String, usize)>,
}

/// A complete community analysis report for one template, or the whole marketplace.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CommunityAnalysisReport {
    pub generated_at: DateTime<Utc>,
    /// The template name analyzed, or `"all"` for a marketplace-wide report.
    pub scope: String,
    pub usage: UsageAnalytics,
    pub feedback: FeedbackAnalysis,
    pub trends: TrendReport,
    pub issues: IssueDetection,
    pub suggestions: Vec<String>,
    pub insights: CommunityInsights,
}

/// Rolling window (in days) used to compare recent vs. prior activity for trend detection.
const DEFAULT_TREND_WINDOW_DAYS: i64 = 7;
/// Minimum number of bug reports before a template is flagged for community issue detection.
const BUG_REPORT_FLAG_THRESHOLD: usize = 3;

// ─── Report generation ──────────────────────────────────────────────────────

/// Generate a full community analysis report for `name`, or for every
/// template in the local registry when `name` is `None`.
pub async fn generate_report(name: Option<&str>) -> Result<CommunityAnalysisReport> {
    let registry = templates::load_registry().await?;
    let entries: Vec<TemplateEntry> = match name {
        Some(n) => registry
            .templates
            .into_iter()
            .filter(|t| t.name == n)
            .collect(),
        None => registry.templates,
    };

    if let Some(n) = name {
        if entries.is_empty() {
            anyhow::bail!("Template '{}' not found in registry", n);
        }
    }

    let usage_events = load_usage_events().unwrap_or_default();
    let feedback = load_feedback(name).unwrap_or_default();

    let usage = build_usage_analytics(&entries, &usage_events, name);
    let feedback_analysis = build_feedback_analysis(&feedback);
    let trends = build_trend_report(&usage_events, name, DEFAULT_TREND_WINDOW_DAYS);
    let issues = build_issue_detection(&entries, &feedback);
    let insights = build_community_insights(&entries);
    let suggestions = build_suggestions(&entries, &feedback_analysis, &issues);

    Ok(CommunityAnalysisReport {
        generated_at: Utc::now(),
        scope: name
            .map(str::to_string)
            .unwrap_or_else(|| "all".to_string()),
        usage,
        feedback: feedback_analysis,
        trends,
        issues,
        suggestions,
        insights,
    })
}

fn build_usage_analytics(
    entries: &[TemplateEntry],
    events: &[UsageEvent],
    scope: Option<&str>,
) -> UsageAnalytics {
    let scoped: Vec<&UsageEvent> = match scope {
        Some(n) => events.iter().filter(|e| e.template == n).collect(),
        None => events.iter().collect(),
    };

    let mut counts: HashMap<String, usize> = HashMap::new();
    let mut by_action: HashMap<String, usize> = HashMap::new();
    for e in &scoped {
        *counts.entry(e.template.clone()).or_insert(0) += 1;
        *by_action.entry(e.action.label().to_string()).or_insert(0) += 1;
    }

    let mut top_templates: Vec<(String, usize)> = counts.into_iter().collect();
    top_templates.sort_by(|a, b| b.1.cmp(&a.1).then_with(|| a.0.cmp(&b.0)));
    top_templates.truncate(10);

    let lifetime_downloads: u32 = entries.iter().map(|t| t.downloads).sum();

    UsageAnalytics {
        total_logged_events: scoped.len(),
        lifetime_downloads,
        top_templates,
        events_by_action: by_action,
    }
}

fn build_feedback_analysis(feedback: &[FeedbackEntry]) -> FeedbackAnalysis {
    let ratings: Vec<f32> = feedback
        .iter()
        .filter_map(|f| f.rating.map(|r| r as f32))
        .collect();
    let average_rating = if ratings.is_empty() {
        None
    } else {
        Some(ratings.iter().sum::<f32>() / ratings.len() as f32)
    };

    let mut sentiment = SentimentBreakdown::default();
    let mut issue_keywords: HashMap<String, usize> = HashMap::new();
    let mut feature_requests: Vec<String> = Vec::new();

    for f in feedback {
        // Prefer the explicit star rating for sentiment when available;
        // otherwise fall back to the feedback category.
        match f.rating {
            Some(r) if r >= 4 => sentiment.positive += 1,
            Some(3) => sentiment.neutral += 1,
            Some(_) => sentiment.negative += 1,
            None => match f.category {
                FeedbackCategory::Praise => sentiment.positive += 1,
                FeedbackCategory::Bug => sentiment.negative += 1,
                FeedbackCategory::FeatureRequest
                | FeedbackCategory::Question
                | FeedbackCategory::Other => sentiment.neutral += 1,
            },
        }

        if matches!(f.category, FeedbackCategory::Bug) {
            let lower = f.comment.to_lowercase();
            for kw in BUG_KEYWORDS {
                if lower.contains(kw) {
                    *issue_keywords.entry((*kw).to_string()).or_insert(0) += 1;
                }
            }
        }

        if matches!(f.category, FeedbackCategory::FeatureRequest) {
            feature_requests.push(f.comment.clone());
        }
    }

    let mut common_issues: Vec<(String, usize)> = issue_keywords.into_iter().collect();
    common_issues.sort_by(|a, b| b.1.cmp(&a.1).then_with(|| a.0.cmp(&b.0)));
    common_issues.truncate(10);
    feature_requests.truncate(10);

    FeedbackAnalysis {
        total_feedback: feedback.len(),
        average_rating,
        sentiment,
        common_issues,
        feature_requests,
    }
}

fn build_trend_report(events: &[UsageEvent], scope: Option<&str>, window_days: i64) -> TrendReport {
    let now = Utc::now();
    let recent_cutoff = now - Duration::days(window_days);
    let prior_cutoff = now - Duration::days(window_days * 2);

    let mut recent: HashMap<String, usize> = HashMap::new();
    let mut prior: HashMap<String, usize> = HashMap::new();

    for e in events {
        if let Some(n) = scope {
            if e.template != n {
                continue;
            }
        }
        if e.timestamp >= recent_cutoff {
            *recent.entry(e.template.clone()).or_insert(0) += 1;
        } else if e.timestamp >= prior_cutoff {
            *prior.entry(e.template.clone()).or_insert(0) += 1;
        }
    }

    let mut templates: Vec<String> = recent.keys().cloned().collect();
    for t in prior.keys() {
        if !templates.contains(t) {
            templates.push(t.clone());
        }
    }
    templates.sort();

    let mut rising = Vec::new();
    let mut declining = Vec::new();
    let mut steady = Vec::new();

    for t in templates {
        let r = *recent.get(&t).unwrap_or(&0);
        let p = *prior.get(&t).unwrap_or(&0);
        if r > p {
            rising.push(t);
        } else if r < p {
            declining.push(t);
        } else {
            steady.push(t);
        }
    }

    TrendReport {
        rising,
        declining,
        steady,
        window_days,
    }
}

fn build_issue_detection(entries: &[TemplateEntry], feedback: &[FeedbackEntry]) -> IssueDetection {
    let mut flagged = Vec::new();

    for e in entries {
        let mut reasons = Vec::new();

        if let CompatibilityStatus::MalformedMetadata { reason } =
            templates::check_template_compatibility(e)
        {
            reasons.push(format!("Malformed CLI version metadata: {}", reason));
        }
        if e.maintenance == MaintenanceStatus::Deprecated {
            reasons.push("Marked deprecated".to_string());
        }
        if !e.documented {
            reasons.push("Missing documentation".to_string());
        }
        if let Some(sr) = &e.security_review {
            if let Some(findings) = &sr.findings {
                if *findings > 0 {
                    reasons.push(format!("{} unresolved security finding(s)", findings));
                }
            }
        }

        let bug_reports = feedback
            .iter()
            .filter(|f| f.template == e.name && matches!(f.category, FeedbackCategory::Bug))
            .count();
        if bug_reports >= BUG_REPORT_FLAG_THRESHOLD {
            reasons.push(format!("{} bug report(s) from the community", bug_reports));
        }

        if !reasons.is_empty() {
            flagged.push(IssueFlag {
                template: e.name.clone(),
                reasons,
            });
        }
    }

    IssueDetection { flagged }
}

fn build_community_insights(entries: &[TemplateEntry]) -> CommunityInsights {
    let total = entries.len();
    let verified = entries.iter().filter(|e| e.verified).count();
    let documented = entries.iter().filter(|e| e.documented).count();

    let mut tag_counts: HashMap<String, usize> = HashMap::new();
    let mut author_counts: HashMap<String, usize> = HashMap::new();
    for e in entries {
        for tag in &e.tags {
            *tag_counts.entry(tag.to_lowercase()).or_insert(0) += 1;
        }
        if !e.author.trim().is_empty() {
            *author_counts.entry(e.author.clone()).or_insert(0) += 1;
        }
    }

    let mut top_tags: Vec<(String, usize)> = tag_counts.into_iter().collect();
    top_tags.sort_by(|a, b| b.1.cmp(&a.1).then_with(|| a.0.cmp(&b.0)));
    top_tags.truncate(10);

    let mut top_authors: Vec<(String, usize)> = author_counts.into_iter().collect();
    top_authors.sort_by(|a, b| b.1.cmp(&a.1).then_with(|| a.0.cmp(&b.0)));
    top_authors.truncate(10);

    CommunityInsights {
        total_templates: total,
        verified_pct: if total == 0 {
            0.0
        } else {
            (verified as f32 / total as f32) * 100.0
        },
        documented_pct: if total == 0 {
            0.0
        } else {
            (documented as f32 / total as f32) * 100.0
        },
        top_tags,
        top_authors,
    }
}

fn build_suggestions(
    entries: &[TemplateEntry],
    feedback: &FeedbackAnalysis,
    issues: &IssueDetection,
) -> Vec<String> {
    let mut suggestions = Vec::new();

    for e in entries {
        if !e.documented {
            suggestions.push(format!(
                "Add a README to '{}' so users understand how to use it.",
                e.name
            ));
        }
        if !e.verified && e.downloads > 100 {
            suggestions.push(format!(
                "'{}' already has meaningful adoption ({} downloads) — consider submitting it for verification.",
                e.name, e.downloads
            ));
        }
        if matches!(e.maintenance, MaintenanceStatus::Unknown) {
            suggestions.push(format!(
                "Declare a maintenance status for '{}' so users can judge its reliability.",
                e.name
            ));
        }
    }

    if let Some(avg) = feedback.average_rating {
        if avg < 3.0 {
            suggestions.push(format!(
                "Average community rating is {:.1}/5 — prioritise the top reported issues below.",
                avg
            ));
        }
    }

    for (keyword, count) in &feedback.common_issues {
        if *count >= 2 {
            suggestions.push(format!(
                "Multiple reports mention \"{}\" ({} times) — investigate and document a fix.",
                keyword, count
            ));
        }
    }

    if !feedback.feature_requests.is_empty() {
        suggestions.push(format!(
            "{} feature request(s) collected from the community — consider triaging them into the roadmap.",
            feedback.feature_requests.len()
        ));
    }

    for flag in &issues.flagged {
        suggestions.push(format!(
            "Review '{}': {}",
            flag.template,
            flag.reasons.join("; ")
        ));
    }

    suggestions.dedup();
    suggestions
}

// ─── Rendering ───────────────────────────────────────────────────────────────

impl CommunityAnalysisReport {
    pub fn to_json_pretty(&self) -> Result<String> {
        serde_json::to_string_pretty(self).context("Failed to serialize community analysis report")
    }

    /// Render the report as a deterministic, human-readable text summary.
    pub fn to_text(&self) -> String {
        let mut out = String::new();

        out.push_str(&format!(
            "Community Analysis Report — scope: {}\n",
            self.scope
        ));
        out.push_str(&format!(
            "Generated: {}\n\n",
            self.generated_at.to_rfc3339()
        ));

        out.push_str("Usage Analytics\n");
        out.push_str(&format!(
            "  Lifetime downloads (registry): {}\n",
            self.usage.lifetime_downloads
        ));
        out.push_str(&format!(
            "  Locally logged events: {}\n",
            self.usage.total_logged_events
        ));
        if !self.usage.top_templates.is_empty() {
            out.push_str("  Most-active templates (local usage):\n");
            for (name, count) in &self.usage.top_templates {
                out.push_str(&format!("    - {}: {} event(s)\n", name, count));
            }
        }
        out.push('\n');

        out.push_str("Feedback Analysis\n");
        out.push_str(&format!(
            "  Total feedback entries: {}\n",
            self.feedback.total_feedback
        ));
        match self.feedback.average_rating {
            Some(avg) => out.push_str(&format!("  Average rating: {:.1}/5\n", avg)),
            None => out.push_str("  Average rating: no ratings submitted yet\n"),
        }
        out.push_str(&format!(
            "  Sentiment — positive: {}, neutral: {}, negative: {}\n",
            self.feedback.sentiment.positive,
            self.feedback.sentiment.neutral,
            self.feedback.sentiment.negative
        ));
        if !self.feedback.common_issues.is_empty() {
            out.push_str("  Common issue keywords:\n");
            for (kw, count) in &self.feedback.common_issues {
                out.push_str(&format!("    - {} ({})\n", kw, count));
            }
        }
        if !self.feedback.feature_requests.is_empty() {
            out.push_str(&format!(
                "  Feature requests collected: {}\n",
                self.feedback.feature_requests.len()
            ));
        }
        out.push('\n');

        out.push_str(&format!(
            "Trends (last {} days vs. prior {} days)\n",
            self.trends.window_days, self.trends.window_days
        ));
        out.push_str(&format!(
            "  Rising: {}\n",
            if self.trends.rising.is_empty() {
                "—".to_string()
            } else {
                self.trends.rising.join(", ")
            }
        ));
        out.push_str(&format!(
            "  Declining: {}\n",
            if self.trends.declining.is_empty() {
                "—".to_string()
            } else {
                self.trends.declining.join(", ")
            }
        ));
        out.push('\n');

        out.push_str("Issue Detection\n");
        if self.issues.flagged.is_empty() {
            out.push_str("  No issues detected.\n");
        } else {
            for flag in &self.issues.flagged {
                out.push_str(&format!(
                    "  - {}: {}\n",
                    flag.template,
                    flag.reasons.join("; ")
                ));
            }
        }
        out.push('\n');

        out.push_str("Improvement Suggestions\n");
        if self.suggestions.is_empty() {
            out.push_str("  None — everything looks healthy.\n");
        } else {
            for s in &self.suggestions {
                out.push_str(&format!("  - {}\n", s));
            }
        }
        out.push('\n');

        out.push_str("Community Insights\n");
        out.push_str(&format!(
            "  Templates tracked: {}\n",
            self.insights.total_templates
        ));
        out.push_str(&format!("  Verified: {:.0}%\n", self.insights.verified_pct));
        out.push_str(&format!(
            "  Documented: {:.0}%\n",
            self.insights.documented_pct
        ));
        if !self.insights.top_tags.is_empty() {
            let tags: Vec<String> = self
                .insights
                .top_tags
                .iter()
                .map(|(t, c)| format!("{} ({})", t, c))
                .collect();
            out.push_str(&format!("  Popular tags: {}\n", tags.join(", ")));
        }
        if !self.insights.top_authors.is_empty() {
            let authors: Vec<String> = self
                .insights
                .top_authors
                .iter()
                .map(|(a, c)| format!("{} ({})", a, c))
                .collect();
            out.push_str(&format!("  Top contributors: {}\n", authors.join(", ")));
        }

        out
    }
}

// ─── Optional AI narrative ──────────────────────────────────────────────────

/// Ask a locally running Ollama model to turn the structured report into a
/// short natural-language narrative. Returns `None` (never an error) when
/// Ollama isn't installed or reachable, so callers can always fall back to
/// [`CommunityAnalysisReport::to_text`].
pub async fn ai_narrative_summary(report: &CommunityAnalysisReport) -> Option<String> {
    if !crate::utils::ollama::is_ollama_running().await {
        return None;
    }
    let prompt = format!("Analyze this community report: {}", report.to_text());
    crate::utils::ollama::generate(crate::utils::ollama::DEFAULT_MODEL, &prompt, None)
        .await
        .ok()
        .map(|resp| resp.response)
}

// ─── Tests ───────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::utils::templates::{ChangelogEntry, SecurityReview, TemplateSource};

    fn entry(name: &str) -> TemplateEntry {
        TemplateEntry {
            name: name.to_string(),
            description: String::new(),
            version: "1.0.0".to_string(),
            source: TemplateSource::Builtin {
                id: name.to_string(),
            },
            tags: vec![],
            path: None,
            author: String::new(),
            downloads: 0,
            verified: false,
            created_at: String::new(),
            updated_at: String::new(),
            cli_version_min: None,
            cli_version_max: None,
            documented: false,
            maintenance: MaintenanceStatus::Unknown,
            license: None,
            repository: None,
            repository_url: None,
            homepage: None,
            documentation: None,
            categories: vec![],
            featured: false,
            provenance: None,
            security_review: None,
            changelog: None,
        }
    }

    fn feedback(
        template: &str,
        category: FeedbackCategory,
        rating: Option<u8>,
        comment: &str,
    ) -> FeedbackEntry {
        FeedbackEntry {
            template: template.to_string(),
            rating,
            comment: comment.to_string(),
            category,
            submitted_at: Utc::now(),
        }
    }

    // ── classify_feedback ───────────────────────────────────────────────────

    #[test]
    fn classify_feedback_detects_bug_reports() {
        assert_eq!(
            classify_feedback("The mint function panics on overflow", None),
            FeedbackCategory::Bug
        );
    }

    #[test]
    fn classify_feedback_detects_feature_requests() {
        assert_eq!(
            classify_feedback("Would be nice to support batch minting", None),
            FeedbackCategory::FeatureRequest
        );
    }

    #[test]
    fn classify_feedback_detects_praise() {
        assert_eq!(
            classify_feedback("Love this template, thanks!", None),
            FeedbackCategory::Praise
        );
    }

    #[test]
    fn classify_feedback_detects_question() {
        assert_eq!(
            classify_feedback("Does this support mainnet?", None),
            FeedbackCategory::Question
        );
    }

    #[test]
    fn classify_feedback_low_rating_without_keywords_is_bug() {
        assert_eq!(classify_feedback("meh", Some(1)), FeedbackCategory::Bug);
    }

    #[test]
    fn classify_feedback_high_rating_without_keywords_is_praise() {
        assert_eq!(
            classify_feedback("solid", Some(5)),
            FeedbackCategory::Praise
        );
    }

    #[test]
    fn classify_feedback_default_is_other() {
        assert_eq!(
            classify_feedback("neutral comment", Some(3)),
            FeedbackCategory::Other
        );
    }

    // ── FeedbackCategory::from_str ──────────────────────────────────────────

    #[test]
    fn feedback_category_from_str_accepts_known_aliases() {
        assert_eq!(
            "bug".parse::<FeedbackCategory>().unwrap(),
            FeedbackCategory::Bug
        );
        assert_eq!(
            "feature_request".parse::<FeedbackCategory>().unwrap(),
            FeedbackCategory::FeatureRequest
        );
        assert_eq!(
            "PRAISE".parse::<FeedbackCategory>().unwrap(),
            FeedbackCategory::Praise
        );
    }

    #[test]
    fn feedback_category_from_str_rejects_unknown() {
        assert!("nonsense".parse::<FeedbackCategory>().is_err());
    }

    // ── validation ───────────────────────────────────────────────────────────

    #[test]
    fn validate_feedback_input_rejects_empty_comment() {
        assert!(validate_feedback_input("   ", None).is_err());
    }

    #[test]
    fn validate_feedback_input_rejects_out_of_range_rating() {
        assert!(validate_feedback_input("ok", Some(0)).is_err());
        assert!(validate_feedback_input("ok", Some(6)).is_err());
    }

    #[test]
    fn validate_feedback_input_accepts_valid_input() {
        assert!(validate_feedback_input("ok", Some(3)).is_ok());
        assert!(validate_feedback_input("ok", None).is_ok());
    }

    // ── submit/load feedback round trip (isolated temp file) ────────────────

    #[test]
    fn submit_and_load_feedback_round_trip() {
        let tmp = tempfile::tempdir().unwrap();
        let path = tmp.path().join("feedback.jsonl");

        submit_feedback_at(&path, "voting", "Great template, thanks!", Some(5), None).unwrap();
        submit_feedback_at(&path, "voting", "Crashes when quorum is zero", None, None).unwrap();
        submit_feedback_at(
            &path,
            "nft",
            "Please add batch transfer",
            None,
            Some(FeedbackCategory::FeatureRequest),
        )
        .unwrap();

        let all: Vec<FeedbackEntry> = load_jsonl(&path).unwrap();
        assert_eq!(all.len(), 3);

        let voting_only: Vec<FeedbackEntry> =
            all.into_iter().filter(|f| f.template == "voting").collect();
        assert_eq!(voting_only.len(), 2);
        assert!(voting_only
            .iter()
            .any(|f| f.category == FeedbackCategory::Praise));
        assert!(voting_only
            .iter()
            .any(|f| f.category == FeedbackCategory::Bug));
    }

    #[test]
    fn submit_feedback_at_rejects_invalid_input() {
        let tmp = tempfile::tempdir().unwrap();
        let path = tmp.path().join("feedback.jsonl");
        assert!(submit_feedback_at(&path, "voting", "", None, None).is_err());
        assert!(submit_feedback_at(&path, "voting", "ok", Some(9), None).is_err());
    }

    // ── usage tracking round trip ────────────────────────────────────────────

    #[test]
    fn record_and_load_usage_round_trip() {
        let tmp = tempfile::tempdir().unwrap();
        let path = tmp.path().join("usage.jsonl");

        record_usage_at(&path, "voting", UsageAction::Scaffold).unwrap();
        record_usage_at(&path, "voting", UsageAction::Scaffold).unwrap();
        record_usage_at(&path, "nft", UsageAction::Install).unwrap();

        let events: Vec<UsageEvent> = load_jsonl(&path).unwrap();
        assert_eq!(events.len(), 3);
        assert_eq!(events.iter().filter(|e| e.template == "voting").count(), 2);
    }

    // ── build_usage_analytics ────────────────────────────────────────────────

    #[test]
    fn usage_analytics_ranks_most_active_template_first() {
        let entries = vec![entry("voting"), entry("nft")];
        let now = Utc::now();
        let events = vec![
            UsageEvent {
                template: "voting".into(),
                action: UsageAction::Scaffold,
                timestamp: now,
            },
            UsageEvent {
                template: "voting".into(),
                action: UsageAction::Scaffold,
                timestamp: now,
            },
            UsageEvent {
                template: "nft".into(),
                action: UsageAction::Install,
                timestamp: now,
            },
        ];

        let analytics = build_usage_analytics(&entries, &events, None);
        assert_eq!(analytics.total_logged_events, 3);
        assert_eq!(analytics.top_templates[0], ("voting".to_string(), 2));
    }

    #[test]
    fn usage_analytics_sums_lifetime_downloads() {
        let mut a = entry("voting");
        a.downloads = 40;
        let mut b = entry("nft");
        b.downloads = 60;
        let analytics = build_usage_analytics(&[a, b], &[], None);
        assert_eq!(analytics.lifetime_downloads, 100);
    }

    // ── build_feedback_analysis ──────────────────────────────────────────────

    #[test]
    fn feedback_analysis_computes_average_rating() {
        let fb = vec![
            feedback("voting", FeedbackCategory::Praise, Some(5), "great"),
            feedback("voting", FeedbackCategory::Bug, Some(1), "crashes"),
        ];
        let analysis = build_feedback_analysis(&fb);
        assert_eq!(analysis.average_rating, Some(3.0));
        assert_eq!(analysis.sentiment.positive, 1);
        assert_eq!(analysis.sentiment.negative, 1);
    }

    #[test]
    fn feedback_analysis_extracts_common_issue_keywords() {
        let fb = vec![
            feedback("voting", FeedbackCategory::Bug, None, "it crashes on init"),
            feedback("voting", FeedbackCategory::Bug, None, "crashes every time"),
        ];
        let analysis = build_feedback_analysis(&fb);
        assert!(analysis
            .common_issues
            .iter()
            .any(|(kw, count)| kw == "crash" && *count == 2));
    }

    #[test]
    fn feedback_analysis_collects_feature_requests() {
        let fb = vec![feedback(
            "voting",
            FeedbackCategory::FeatureRequest,
            None,
            "please add quorum config",
        )];
        let analysis = build_feedback_analysis(&fb);
        assert_eq!(analysis.feature_requests.len(), 1);
    }

    #[test]
    fn feedback_analysis_handles_no_feedback() {
        let analysis = build_feedback_analysis(&[]);
        assert_eq!(analysis.total_feedback, 0);
        assert_eq!(analysis.average_rating, None);
    }

    // ── build_trend_report ───────────────────────────────────────────────────

    #[test]
    fn trend_report_flags_rising_template() {
        let now = Utc::now();
        let events = vec![
            // 2 events this week
            UsageEvent {
                template: "voting".into(),
                action: UsageAction::Scaffold,
                timestamp: now,
            },
            UsageEvent {
                template: "voting".into(),
                action: UsageAction::Scaffold,
                timestamp: now,
            },
            // 1 event the prior week
            UsageEvent {
                template: "voting".into(),
                action: UsageAction::Scaffold,
                timestamp: now - Duration::days(10),
            },
        ];
        let trend = build_trend_report(&events, None, 7);
        assert!(trend.rising.contains(&"voting".to_string()));
    }

    #[test]
    fn trend_report_flags_declining_template() {
        let now = Utc::now();
        let events = vec![
            UsageEvent {
                template: "nft".into(),
                action: UsageAction::Scaffold,
                timestamp: now - Duration::days(10),
            },
            UsageEvent {
                template: "nft".into(),
                action: UsageAction::Scaffold,
                timestamp: now - Duration::days(11),
            },
        ];
        let trend = build_trend_report(&events, None, 7);
        assert!(trend.declining.contains(&"nft".to_string()));
    }

    // ── build_issue_detection ────────────────────────────────────────────────

    #[test]
    fn issue_detection_flags_deprecated_and_undocumented_templates() {
        let mut e = entry("legacy");
        e.maintenance = MaintenanceStatus::Deprecated;
        e.documented = false;

        let issues = build_issue_detection(&[e], &[]);
        assert_eq!(issues.flagged.len(), 1);
        assert!(issues.flagged[0]
            .reasons
            .iter()
            .any(|r| r.contains("deprecated")));
        assert!(issues.flagged[0]
            .reasons
            .iter()
            .any(|r| r.contains("documentation")));
    }

    #[test]
    fn issue_detection_flags_security_findings() {
        let mut e = entry("token");
        e.security_review = Some(SecurityReview {
            status: "audited".to_string(),
            audited_at: Some("2026-01-01".to_string()),
            auditor: Some("Auditor".to_string()),
            findings: Some(2),
            score: Some(80.0),
        });
        e.documented = true;

        let issues = build_issue_detection(&[e], &[]);
        assert_eq!(issues.flagged.len(), 1);
        assert!(issues.flagged[0]
            .reasons
            .iter()
            .any(|r| r.contains("security finding")));
    }

    #[test]
    fn issue_detection_flags_repeated_bug_reports() {
        let mut e = entry("dex");
        e.documented = true;
        let fb = vec![
            feedback("dex", FeedbackCategory::Bug, None, "crashes"),
            feedback("dex", FeedbackCategory::Bug, None, "broken swap"),
            feedback("dex", FeedbackCategory::Bug, None, "fails on init"),
        ];

        let issues = build_issue_detection(&[e.clone()], &fb);
        assert_eq!(issues.flagged.len(), 1);
        assert!(issues.flagged[0]
            .reasons
            .iter()
            .any(|r| r.contains("bug report")));
        e.security_review = None; // no-op, keeps `e` used
    }

    #[test]
    fn issue_detection_skips_healthy_templates() {
        let mut e = entry("healthy");
        e.documented = true;
        e.maintenance = MaintenanceStatus::Active;
        let issues = build_issue_detection(&[e], &[]);
        assert!(issues.flagged.is_empty());
    }

    // ── build_community_insights ─────────────────────────────────────────────

    #[test]
    fn community_insights_computes_percentages_and_popularity() {
        let mut a = entry("voting");
        a.verified = true;
        a.documented = true;
        a.tags = vec!["governance".to_string(), "dao".to_string()];
        a.author = "Alice".to_string();

        let mut b = entry("nft");
        b.tags = vec!["nft".to_string(), "dao".to_string()];
        b.author = "Alice".to_string();

        let insights = build_community_insights(&[a, b]);
        assert_eq!(insights.total_templates, 2);
        assert_eq!(insights.verified_pct, 50.0);
        assert_eq!(insights.documented_pct, 50.0);
        assert_eq!(insights.top_tags[0], ("dao".to_string(), 2));
        assert_eq!(insights.top_authors[0], ("Alice".to_string(), 2));
    }

    #[test]
    fn community_insights_handles_empty_registry() {
        let insights = build_community_insights(&[]);
        assert_eq!(insights.total_templates, 0);
        assert_eq!(insights.verified_pct, 0.0);
    }

    // ── build_suggestions ────────────────────────────────────────────────────

    #[test]
    fn suggestions_recommend_docs_for_undocumented_templates() {
        let e = entry("bare");
        let feedback = build_feedback_analysis(&[]);
        let issues = IssueDetection::default();
        let suggestions = build_suggestions(&[e], &feedback, &issues);
        assert!(suggestions.iter().any(|s| s.contains("README")));
    }

    #[test]
    fn suggestions_flag_low_average_rating() {
        let fb = vec![
            feedback("voting", FeedbackCategory::Bug, Some(1), "crashes"),
            feedback("voting", FeedbackCategory::Bug, Some(2), "buggy"),
        ];
        let feedback_analysis = build_feedback_analysis(&fb);
        let suggestions = build_suggestions(&[], &feedback_analysis, &IssueDetection::default());
        assert!(suggestions
            .iter()
            .any(|s| s.contains("Average community rating")));
    }

    #[test]
    fn suggestions_surface_feature_request_count() {
        let fb = vec![feedback(
            "voting",
            FeedbackCategory::FeatureRequest,
            None,
            "please add X",
        )];
        let feedback_analysis = build_feedback_analysis(&fb);
        let suggestions = build_suggestions(&[], &feedback_analysis, &IssueDetection::default());
        assert!(suggestions.iter().any(|s| s.contains("feature request")));
    }

    // ── report rendering ─────────────────────────────────────────────────────

    #[test]
    fn report_to_text_contains_all_sections() {
        let report = CommunityAnalysisReport {
            generated_at: Utc::now(),
            scope: "all".to_string(),
            usage: build_usage_analytics(&[], &[], None),
            feedback: build_feedback_analysis(&[]),
            trends: build_trend_report(&[], None, 7),
            issues: IssueDetection::default(),
            suggestions: vec!["Do the thing".to_string()],
            insights: build_community_insights(&[]),
        };
        let text = report.to_text();
        assert!(text.contains("Usage Analytics"));
        assert!(text.contains("Feedback Analysis"));
        assert!(text.contains("Trends"));
        assert!(text.contains("Issue Detection"));
        assert!(text.contains("Improvement Suggestions"));
        assert!(text.contains("Community Insights"));
    }

    #[test]
    fn report_to_json_pretty_round_trips() {
        let report = CommunityAnalysisReport {
            generated_at: Utc::now(),
            scope: "voting".to_string(),
            usage: build_usage_analytics(&[], &[], None),
            feedback: build_feedback_analysis(&[]),
            trends: build_trend_report(&[], None, 7),
            issues: IssueDetection::default(),
            suggestions: vec![],
            insights: build_community_insights(&[]),
        };
        let json = report.to_json_pretty().unwrap();
        let parsed: CommunityAnalysisReport = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed.scope, "voting");
    }

    #[test]
    fn changelog_entry_and_source_are_constructible() {
        // Sanity check that the imports used above compile and are usable,
        // guarding against accidental drift in `utils::templates`.
        let _ = ChangelogEntry {
            version: "1.0.0".to_string(),
            date: "2026-01-01".to_string(),
            notes: "initial release".to_string(),
        };
    }
}
